functionsDirectory = "/Users/openclaw/.openclaw/workspace/tesla-catalyst-graph/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/openclaw/.openclaw/workspace/tesla-catalyst-graph/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/openclaw/.openclaw/workspace/tesla-catalyst-graph/netlify/functions"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/success/single"
to = "/?upgrade=single"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/success/trader"
to = "/?upgrade=active_trader"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/success/institutional"
to = "/?upgrade=institutional"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]