export const catalysts = [
  // AUTONOMY
  {
    id: "cybercab_production",
    label: "Cybercab Production Start",
    category: "autonomy",
    weight: 0.15,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.94,
    updated: "Apr 17, 2026",
    description: [
      "🆕 Apr 25, 2026: Tesla confirms Cybercab has NO production cap as ramp begins — unlike previous models with fixed production targets, Cybercab output will scale demand-driven; Musk confirmed on Q1 call that volumes will ramp 'exponentially by end of 2026'; signals extreme confidence in demand and manufacturing execution (notateslaapp)",
      "🆕 Apr 20, 2026: 14 Cybercab units WITHOUT steering wheels spotted at Giga Texas — strong confirmation that production-spec autonomous Cybercabs are now rolling off the line; no-steering-wheel design (original spec) being built alongside wheel-equipped units for regulatory purposes; production ramp accelerating",
      "🆕 Apr 17, 2026: Teslarati confirms Tesla's 'Cybercab robotaxi golden era is officially underway' — volume production ramp live at Giga Texas, autonomous Robotaxi service confirmed for 7 new U.S. cities, late 2026 commercial Austin launch reaffirmed; production timeline validated by drone footage + crash testing evidence",
      "🆕 Apr 15, 2026: Drone footage (Teslarati) reveals 50+ Tesla Cybercab units undergoing crash testing at Giga Texas — confirms active production ramp proceeding on schedule; late 2026 commercial robotaxi launch in Austin reaffirmed as target",
      "🚀 MASS PRODUCTION STARTED: Cybercab formally entered production at Giga Texas in April 2026 — first unit rolled off in February; now targeting several hundred units/week ramp",
      "⚠️ Apr 11, 2026: Reports emerge that early production Cybercabs include a steering wheel — departure from the original 'no steering wheel, no pedals' design promise; likely a regulatory concession for near-term deployment; complicates the pure-autonomy narrative and may signal CA/NHTSA pressure to retain manual override capability",
      "🆕 Apr 8, 2026 (PM): 60 Cybercabs spotted at Giga Texas (Teslarati) — concrete evidence of live production ramp; Musk confirmed initial output follows classic S-curve toward hundreds of units/week",
      "Model S and Model X production officially ended — Fremont factory space now freed for Optimus; Giga Texas pivoting Cybercab + Optimus focus",
      "Eliminates steering wheel and pedals — purpose-built for autonomy",
      "💡 UNIT ECONOMICS (Apr 10, 2026): A regular Tesla sale generates ~$3K one-time profit. A Cybercab costing ~$15K to manufacture is projected to generate $30K–$50K in annual profit running autonomously — turning each vehicle into a nonstop cash machine. This flips Tesla's model from 'sell cars' to 'own a fleet of income-generating robots.' Each Cybercab = ~10–17x the lifetime earnings of a traditional vehicle sale.",
      "Manufacturing cost target: $40K–$45K/unit (vs Waymo's ~$200K)",
      "New charge port and improved FSD cameras confirmed in first impressions (Mar 22)",
      "Wheelchair-height seats; ambient lighting; refined interior",
      "TSMC hardware batches in early validation as of March 2026",
      "Unboxed manufacturing process being deployed for Cybercab line",
      "Morgan Stanley (Mar 18, 2026): officially classified Tesla as AI platform company, Cybercab as core catalyst",
      "⚠️ RISK (Apr 2026): 3 Cybercab team leaders departed within weeks — program manager, ride-hailing infrastructure director, AND assembly leader all gone; FSD reliability concerns cited",
    ]
  },
  {
    id: "robotaxi_austin",
    label: "Robotaxi Launch Austin",
    category: "autonomy",
    weight: 0.12,
    status: "achieved",
    expected: "Q2 2025",
    likelihood: 0.95,
    updated: "Apr 17, 2026",
    description: [
      "🆕 Apr 14, 2026: Cybercab testing officially confirmed in Florida — first out-of-Texas state deployment; Miami, Orlando, Tampa all on 1H 2026 roadmap; Florida presence signals active pre-launch ops",
      "🆕 Apr 11, 2026: BofA (Alexander Perry) calls Tesla the 'clear leader in autonomous driving' — vision-only approach more cost-effective and scalable than lidar competitors. Morgan Stanley (Andrew Percoco) reiterates robotaxi flywheel thesis: fleet scaling → FSD improvement → re-accelerates core auto demand. Both analysts naming robotaxi as THE key 2026 catalyst for TSLA.",
      "Morgan Stanley (Apr 5, 2026): 'Scaling the unsupervised robotaxi fleet is the most important catalyst for $TSLA this year' — each incremental mile accelerates FSD learning → higher attach rates → re-accelerates auto demand → improves FCF. Stock expected to trade in close correlation to robotaxi fleet scaling + 7-city expansion by end of June.",
      "⚠️ JPMorgan (Apr 6, 2026): Analyst Ryan Brinkman reiterates Underweight / $145 PT — 60% downside from current levels; record unsold inventory (50K+ Q1 build) cited as primary bear case; Dec 2026 target date",
      "Musk (Apr 7 context): Confirming robotaxi expansion to 9 cities in 2026; Cybercab production officially started; Megapack 3 announced",
      "LIVE — Austin fleet operational as of mid-2025",
      "🆕 Apr 18, 2026: Tesla officially launches unsupervised robotaxi service in Dallas and Houston — 573-vehicle Model Y fleet with no driver or monitor in front seats; full multi-city expansion executing on schedule; first cities beyond Austin to receive driverless service; confirmed by Reuters, notateslaapp, Wikipedia",
      "🆕 Apr 21, 2026: Total cross-fleet unsupervised vehicles: 17 (up from 13 on Apr 17) — fleet growing steadily; Austin 96 total, Dallas 2, Houston 2 just launched — source: robotaxitracker.com / Autolane",
      "🆕 Apr 17, 2026: Austin unsupervised robotaxi fleet reaches 13 vehicles — up from 12 yesterday, 9 last week; slow but steady expansion continues; service area now 12x original launch size after 4 geofence expansions since mid-2025 — source: NextBigFuture / robotaxitracker.com",
      "🆕 Apr 16, 2026: Tesla added another unsupervised Model Y robotaxi to Austin fleet — total unsupervised vehicles now 12 (up from 9); fleet continues to expand ahead of commercial launch — source: robotaxitracker.com/unsupervised",
      "43 vehicles active (30d) | 9 unsupervised active | 28 Cybercabs test fleet | 51 inactive (30d unseen) | 94 total ever — source: robotaxitracker.com (Apr 7, 2026)",
      "Bay Area: 462 total (+5 this week, +7 this week, 68 in 30d) — supervised only; 3 Cybercabs test fleet",
      "🏁 Austin fleet total mileage: ~1.01M+ miles | current rate: ~4,700 mi/day",
      "Austin pricing: avg fare $5.13 | avg 3.7 mi/ride | 1,657 logged rides (+15 since Apr 6) | 64 riders community",
      "Unsupervised rides last 7d: 27.8% (15 of 54 rides this week)",
      "Coverage area: 244 sq mi — majority supervised; unsupervised pilot expanded into downtown (crossed Colorado River, Mar 31)",
      "Bay Area: 453 vehicles deployed, 1,094 sq mi coverage — human-driver supervised ride hail only; awaiting CA regulatory approval",
      "MAJOR (Mar 31): Unsupervised geofence more than doubled — now covers downtown Austin north of Colorado River",
      "FSD update 2026.8.6 rolling out globally Apr 3 — hints at FSD v14 imminent Europe launch ahead of Apr 10 RDW approval date",
      "Min ride age lowered to 8 years old (with adult present) — expanding consumer access",
      "NHTSA: 28 all-time ADS incident reports, 10 in last 90 days",
    ]
  },
  {
    id: "fsd_unsupervised",
    label: "FSD Unsupervised Rollout",
    category: "autonomy",
    weight: 0.10,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.93,
    updated: "Apr 17, 2026",
    description: [
      "🆕 Apr 11, 2026: Tesla opens FSD outright purchase option in Europe following Netherlands RDW approval — first time EU customers can buy FSD, not just subscribe. Signals confidence in sustained EU regulatory status and unlocks a material new revenue stream from the EU's ~15M Tesla-addressable fleet.",
      "Apr 10, 2026: Netherlands RDW approval CONFIRMED — FSD Supervised now officially cleared for European roads, opening EU subscriber market for first time. First regulatory greenlight outside the US; sets precedent for EU-wide harmonization expected this summer.",
      "✅ Apr 22, 2026 (Q1 deck): FSD moving to subscription-only. Record net new subscriptions in Q1. FSD insurance: Safety Score of 100 available on every FSD mile driven — premium savings can 'more than compensate for the monthly price of FSD.' Netherlands approval clears path for other EU countries. China in progress.",
      "✅ Apr 22, 2026 (Q1 deck): FSD v14.3 inference latency cut 20%. Cumulative FSD miles ~9B+ by end Q1. Digital Optimus = intelligence layer for physical Optimus.",
      "Apr 7, 2026: FSD v14.3 officially released — biggest architectural leap in FSD history",
      "v14.3 is a ground-up rewrite: larger model, new RL training method, completely new vision system, new compiler/runtime",
      "Expected to drive better than a human (better decisions, less robotic), see better in tricky/low-visibility conditions, and react faster",
      "Released 2 days late from internal target — considered on-schedule by Tesla standards",
      "Austin: unsupervised pilot active — ongoing driverless rides logged weekly",
      "Bay Area: 449 vehicles deployed but supervised-only — awaiting CA regulatory approval",
      "⚠️ DISCLOSURE (Apr 3): Tesla confirmed in Senate letter that human operators can take direct remote control of robotaxis in rare cases (at ≤2 mph, up to 10 mph)",
      "FSD v14 won MotorTrend 2026 Driver Assistance System of the Year",
      "🆕 Apr 17, 2026: FSD v14.3.1 rolling out fleet-wide (2026.2.9.7 build) — incremental refinements on top of v14.3 ground-up rewrite; FSD approaching 10 billion cumulative miles ahead of Apr 22 earnings; EU expansion staggered rollout begins Netherlands → Germany/France/Spain by summer",
      "🆕 Apr 14, 2026: FSD approaching 10 billion cumulative miles — up from 8.4B in Feb 2026; Tesla FSD head Ashok Elluswamy stated the Netherlands RDW approval 'will enable global rollout' across EU markets",
      "⚠️ Apr 14, 2026: Morgan Stanley note — 'Investors Need More Proof of Real Autonomy' despite milestone; emphasizes market wants demonstrated unsupervised reliability before re-rating",
      "🆕 Apr 26, 2026: FSD v14.3.2 officially released (build 2026.2.9.8) — unified AI model across Actually Smart Summon, FSD, and Robotaxi; vehicles no longer switch models between parking lot and public road environments; first time fleet-wide and robotaxi fleet share a single neural network; major architectural step toward production-grade unsupervised operation (notateslaapp / basenor)",
      "🆕 Apr 25, 2026: Tesla hits $546M annual recurring revenue from FSD subscriptions — 1.28M active subscribers as of Q1 2026 (+51% YoY); subscription-only model transition now capturing recurring SaaS-style revenue; FSD ARR growing faster than vehicle deliveries, improving long-term unit economics (notateslaapp)",
      "✅ Apr 22, 2026 (Q1 deck): Active FSD Subscriptions 1.28M (+51% YoY from 0.85M in Q1 2025). Cumulative all-time deliveries: 9.2M (+21% YoY).",
      "🇳🇱 Netherlands RDW approval: CONFIRMED April 10, 2026 — first EU regulatory greenlight; EU-wide rollout expected summer 2026",
      "🆕 Apr 23, 2026 (Q1 Earnings Call): Musk CONFIRMED HW3 cannot achieve Unsupervised FSD — 'simply does not have the capability'; only 1/8 memory bandwidth of HW4/AI4; FSD v12.6.4 was last HW3 update (Mar 2025); Musk offered free HW3→HW4 retrofit path. V14 Lite for HW3 (supervised only) releasing by end of June.",
      "Risk: NHTSA has not yet granted 'fully autonomous' commercial approval",
    ]
  },
  {
    id: "robotaxi_expansion",
    label: "Robotaxi Multi-City",
    category: "autonomy",
    weight: 0.08,
    status: "in_progress",
    expected: "1H 2026",
    likelihood: 0.78,
    updated: "Apr 27, 2026",
    description: [
      "🆕 Apr 27, 2026: Post-earnings consensus solidifying — Musk said robotaxi will 'not be super material this year'; targets 'dozen or so states' with Cybercab + Model Y fleet but scale limited in 2026; Motley Fool / BI post-earnings analysis flag this as chief new bear anchor alongside $25B capex; 2027 is the base case for material revenue contribution",
      "⚠️ Apr 22, 2026 (Earnings Call): Tesla quietly slips 5-city 1H 2026 robotaxi commitments — Phoenix, Miami, Orlando, Tampa, Las Vegas now listed as 'preparations underway' with no firm date; prior language was explicit 1H 2026 target; only Dallas + Houston confirmed live; Electrek, Business Insider flag the language change as a material timeline slip; 5-city 2H 2026 or later now the base case",
      "🆕 Apr 22, 2026: Tesla files permits for first robotaxi-only Supercharger stations in Arizona — dedicated V4 fleet charging hubs exclusively for Cybercab fleet (not public-use); first physical fleet infrastructure for autonomous operations; sites in Waymo's home territory signal competitive intent; private charging enables optimized scheduling, reduced downtime, and bidirectional energy integration (Electrek / notateslaapp / Teslarati)",
      "🆕 Apr 21, 2026: Fleet growth data (robotaxitracker.com / Autolane): TOTAL FLEET 611 vehicles cumulative — Bay Area 511, Austin 96, Dallas 2, Houston 2. UNSUPERVISED count: 17 active. Fleet curve shows steep ramp through Apr 2026 driven by Bay Area scale-up; Austin steady at ~96; Dallas/Houston just launched at 2 vehicles each confirming live operations but early stage",
      "🆕 Apr 20, 2026 (6pm ET): Musk on X: 'We expect to have fully autonomous vehicles in somewhere between a quarter and half of the United States' by end 2026 — robotaxis targeting 'dozens of major cities'; caveat: same promise made for end of 2025 (half of US population) and missed badly; aspirational language flagged by Motley Fool / Reuters",
      "🆕 Apr 20, 2026: Electrek (Apr 19) calls Dallas/Houston launch 'another stock pump before earnings' — small initial geofences with limited vehicles, not real commercial scale; Engadget confirms small sections only; skepticism about autonomy pace intensifying just before Apr 22 earnings call; bull/bear tension at maximum",
      "🆕 Apr 18, 2026: Tesla launches UNSUPERVISED robotaxi service in Dallas and Houston — 573-vehicle fleet, Model Y SUVs with no driver or monitor in front seats; CEO Musk reposted 'Try Tesla Robotaxi in Dallas & Houston!'; small initial geofences, no fleet size or pricing disclosed; first multi-city expansion beyond Austin — confirms 1H 2026 expansion is executing on schedule (Reuters / notateslaapp / Wikipedia)",
      "🆕 Apr 17, 2026: Teslarati confirms autonomous Robotaxi service expansion to 7 new U.S. cities confirmed — concrete milestone alongside Cybercab volume production ramp; multi-city 1H 2026 target now actively in execution",
      "🆕 Apr 14, 2026: Cybercab testing has officially begun in Florida — first confirmed presence in a key expansion state; Miami, Orlando, and Tampa all on the 1H 2026 roadmap; this is the first concrete signal that FL launch is imminent",
      "🆕 Apr 8, 2026: ~60 Tesla Model Y vehicles spotted staged in Phoenix parking lot — active staging ground for imminent robotaxi launch (notateslaapp.com); fleet features rear camera washers confirming robotaxi hardware spec",
      "Las Vegas, Dallas, Houston, Miami, Orlando, Phoenix, Tampa all listed as '1H 2026' on robotaxitracker.com city map (confirmed Apr 3)",
      "Bay Area (CA): 449 vehicles active — human-driver only, 1,094 sq mi coverage",
      "37 Cybercabs spotted across 7 regions (28 test fleet active in Austin) as of Apr 7, 2026",
      "Planned 1H 2026 expansion: Dallas TX, Houston TX, Las Vegas NV",
      "Planned 1H 2026 expansion: Miami FL, Orlando FL, Phoenix AZ, Tampa FL",
      "Evidence emerging of imminent Las Vegas and Dallas launches (notateslaapp.com, Mar 31)",
      "Austin unsupervised geofence 2x+ expansion (crossed river into downtown) validates confidence for multi-city",
      "Q4 2025 earnings call: '25–50% of US with fully autonomous vehicles by end of 2026'",
      "BofA SOTP: Robotaxi business valued at ~$750B — ~52% of Tesla's total market cap at scale",
      "Key risk: CA regulatory approval needed before Bay Area fleet can go unsupervised",
      "Key risk: NHTSA federal approval still pending for commercial AV operation",
    ]
  },
  {
    id: "robotaxi_app",
    label: "Robotaxi Public App Launch",
    category: "autonomy",
    weight: 0.06,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.60,
    updated: "Apr 27, 2026",
    description: [
      "🆕 Apr 24, 2026: Tesla officially launches Robotaxi app for Android — was iOS-only since Austin launch; Android release opens the platform to the majority of smartphone users; consumer accessibility milestone ahead of multi-city expansion; app still invite/region-limited but broader platform parity achieved (notateslaapp)",
      "⚠️ Apr 22, 2026 (Earnings Call): With 5 planned expansion cities slipped to vague 'preparations underway,' broad public app launch tied to multi-city scale is delayed; only Austin, Dallas, Houston operational; mass-market consumer app requires more cities to be viable — Q3/Q4 2026 more likely than Q3",
      "🆕 Apr 21, 2026: Tesla Spring Update v2026.14+ rolling out — rear passenger display now features fully interactive navigation map while driving, a capability previously reserved for Tesla Robotaxi; Tesla pushing robotaxi-grade features to all owner vehicles, accelerating consumer familiarity with autonomous UX (Teslarati)",
      "🆕 Apr 15, 2026: Tesla Spring 2026 software update introduces a standalone Self-Driving subscription app and 'Hey Grok' xAI voice assistant — significant step toward a consumer-facing autonomous ride ecosystem; reduces friction to FSD adoption",
      "Consumer-facing Tesla Robotaxi app for public ride booking",
      "Currently ride access is invite-only / limited beta in Austin",
      "App launch would signal readiness for mass-market commercial operation",
      "Key unlock for network effects — more rides = more training data = better FSD",
      "Likely tied to multi-city expansion timeline in 1H–2H 2026",
      "Uber/Lyft competitive threat if Tesla opens app broadly — or potential partnership",
      "🆕 Apr 12, 2026: Tesla Robotaxi app received a major update (TeslaNorth) — new features and UI improvements, strengthening app readiness ahead of multi-city expansion",
      "📱 App v26.3.0 (Apr 3, 2026): Apple Pay + Google Pay support added — Android app assets suggest broad platform launch imminent; map UI redesign underway",
    ]
  },
  {
    id: "fsd_v15",
    label: "FSD v15 — Full Autonomy",
    category: "autonomy",
    weight: 0.08,
    status: "upcoming",
    expected: "Q3–Q4 2026",
    likelihood: 0.60,
    updated: "Apr 17, 2026",
    description: [
      "🆕 Apr 17, 2026: Reddit AI5 discussions confirm FSD v15 is an AI5-only release — v14 Lite targeting late June 2026 for HW4 hardware as a bridge; v15 full autonomy milestone pushed to AI5 volume production window (2027); near-term unsupervised scaling relies on v14.x on AI4/AI4.5",
      "🆕 Apr 12, 2026: Morgan Stanley (Forbes) — specifically calls robotaxi pickup/dropoff challenges 'actually quite solvable' and projects 'more unsupervised vehicles on road throughout 2026'; reiterates confidence in v15 timeline as the flywheel accelerator for core auto demand",
      "🆕 Apr 9, 2026: FSD v14.3 (ground-up rewrite) now in wider rollout — v15 is the next major architectural milestone targeting zero-intervention unsupervised operation",
      "v15 expected to cross the 'no human needed' threshold — the regulatory and commercial unlock for mass robotaxi deployment",
      "Netherlands RDW European approval expected Apr 10, 2026 — first regulatory greenlight outside US, sets precedent for v15 global rollout",
      "v14.3 MLIR compiler rewrite (Apr 2026) dramatically reduced inference latency — v15 builds on this foundation with larger model and expanded RL training data",
      "Direct dependency for Cybercab production viability — Cybercab ships with no steering wheel, requires v15-class autonomy",
      "FSD licensing deals with third-party OEMs contingent on v15 reliability benchmarks",
      "Each major version has shipped ~2 quarters apart — v15 timeline aligns with Q3 2026 if cadence holds",
    ]
  },
  {
    id: "fsd_licensing",
    label: "FSD Licensed to OEMs",
    category: "autonomy",
    weight: 0.07,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.30,
    updated: "Mar 22, 2026",
    description: [
      "Tesla licensing FSD software stack to other automakers",
      "Near 100% gross margin revenue — no hardware cost to Tesla",
      "Musk has confirmed discussions with 'several' OEMs",
      "No public deal announced as of March 2026",
      "Would transform Tesla into an AI software licensor — massive TAM expansion",
      "Risk: OEMs may prefer developing in-house or using Waymo/Mobileye alternatives",
      "If even one major OEM deal closes, this is a significant re-rating catalyst",
    ]
  },
  {
    id: "regulatory_approval",
    label: "Federal AV Regulatory Approval",
    category: "autonomy",
    weight: 0.08,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.42,
    updated: "Apr 10, 2026",
    description: [
      "🆕 Apr 8, 2026: NHTSA closed Smart Summon investigation — fewer than 1% of uses resulted in incidents, zero injuries (Benzinga). Win, but narrow.",
      "⚠️ Apr 10, 2026: California DMV continues to withhold 'unsupervised' AV permits following a string of high-profile FSD-related accidents in early 2026 — TSLA 8th consecutive weekly loss correlates with this regulatory overhang; CA remains the largest blocked market.",
      "⚠️ Apr 8, 2026: NHTSA opened separate FSD investigation — reports of FSD-equipped vehicles running red lights, making illegal turns, entering oncoming traffic. New headwind.",
      "NHTSA federal framework needed for commercial autonomous operation at scale",
      "Currently Tesla operates under state-level exemptions (TX, CA)",
      "Netherlands RDW approval (Europe): hard date April 10, 2026",
      "NHTSA SGO 2021-01 ADS reporting active — Tesla has 28 all-time incident reports",
      "10 incidents reported in last 90 days — most property damage, no fatalities",
      "GLJ Research flagged: Tesla accident frequency still above human driving baseline",
      "Federal approval would unlock all 50 states simultaneously — enormous scale catalyst",
      "Risk: new FSD probe creates additional regulatory overhang ahead of unsupervised scaling",
    ]
  },

  // ROBOTICS / AI
  {
    id: "optimus_production",
    label: "Optimus Mass Production",
    category: "robotics",
    weight: 0.12,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.78,
    updated: "Apr 24, 2026",
    description: [
      "🆕 Apr 24, 2026 (Q1 Earnings Call): Musk confirmed Optimus Fremont production starts 'late July or August' — most concrete timeline yet; second factory at Giga Texas targets summer 2027; Optimus Gen 3 reveal pushed closer to production start; Musk cautioned ramp rates are 'impossible to predict' with 10,000+ unique parts; initial output will be slow",
      "✅ Apr 22, 2026 (Q1 Outlook): Tesla OFFICIAL: 'First-generation production lines for Optimus are being installed in anticipation of volume production.' Fremont gen-1 line (1M/yr) + Giga Texas gen-2 (10M/yr long-term) both under construction per manufacturing table.",
      "✅ Apr 22, 2026 (Q1 shareholder deck): Fremont plant actively converting Model S/X production lines to Optimus factory — confirmed for Q2 start. Giga Texas being prepared for 2nd-gen Optimus line with long-term 10M robot/year capacity. No hard shipment numbers disclosed yet.",
      "🆕 Apr 17, 2026: Tesla files Optimus Gen 3 mechanical blueprint patents — joint designs, actuator architecture, chassis geometry locked in for mass manufacturing",
      "🆕 Apr 16, 2026: Gen 3 enters mass production phase — concurrent ramp at Giga Texas and GigaShanghai; first units targeting internal factory deployment",
      "🆕 Apr 16, 2026: Tesla China president Wang Hao — GigaShanghai is the 'golden key' to Optimus mass production; 1M units/year long-term capacity target",
      "Model S and Model X production officially ended — factory space now freed for Optimus",
      "Currently ~1,000 units/yr internal deployment pace — target 10K+ by end 2026",
      "Musk long-term thesis: Optimus becomes 80% of Tesla's total value",
      "Key risk: fine motor skill reliability still unproven for complex manufacturing tasks",
      "Key risk: production ramp historically difficult — Cybertruck ramp as cautionary tale",
    ]
  },
  {
    id: "optimus_external",
    label: "Optimus External Sales",
    category: "robotics",
    weight: 0.08,
    status: "upcoming",
    expected: "2027",
    likelihood: 0.30,
    updated: "Apr 23, 2026",
    description: [
      "🆕 Apr 23, 2026 (Q1 Earnings Call): Musk confirmed Optimus external sales 'probably' in 2027 — said it will 'probably be made useful outside of Tesla sometime next year'; slides timeline from Q4 2026 to 2027; consistent with earlier TheNextWeb confirmation of 2027 commercial deployment.",
      "First external customer deliveries of Optimus humanoid robot",
      "Target price not officially confirmed — estimated $20K–$30K/unit",
      "Initial customers likely industrial/warehouse clients, not consumers",
      "External sales would mark Tesla's entry into humanoid robotics market",
      "TAM: Morgan Stanley estimates global humanoid robot market at $6T by 2040",
      "Competition: Boston Dynamics, Figure AI, 1X, Apptronik all racing to scale",
      "InvestAnswers model: 100K external units/yr @ $20K margin = $2B/yr, growing exponentially",
    ]
  },
  {
    id: "optimus_factory",
    label: "Optimus In-Factory Deployment",
    category: "robotics",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.70,
    updated: "Mar 23, 2026",
    description: [
      "Optimus units currently working inside Tesla Gigafactories",
      "Tasks: battery cell handling, parts sorting, wiring harness assembly",
      "Proof-of-concept phase — each successful task expands scope",
      "Elon confirmed on Q4 2025 earnings call: 'Optimus doing useful work at Giga Texas'",
      "Internal deployment de-risks external sales — real-world validation at scale",
      "Cost savings from replacing human labor feeds back into production cost reduction",
    ]
  },
  {
    id: "dojo_v2",
    label: "Dojo Supercomputer Expansion",
    category: "robotics",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.75,
    updated: "Apr 15, 2026",
    description: [
      "Dojo: Tesla's custom AI training supercomputer built on D1 chips",
      "Designed to process massive video datasets from Tesla fleet (8.4B miles)",
      "Reduces reliance on Nvidia H100/H200 GPUs — significant cost reduction",
      "Dojo v2 expansion underway — exaFLOP-scale compute being added",
      "Training FSD and Optimus models simultaneously",
      "Morgan Stanley estimated Dojo could add $500B to Tesla's valuation at full scale",
      "🆕 Apr 15, 2026: Elon Musk confirmed Dojo3 chip is in development — next-gen successor to D1/D2 architecture; timeline TBD",
      "Risk: Nvidia still dominant; Dojo timeline has slipped before",
    ]
  },
  {
    id: "hw5_chip",
    label: "HW5 AI Chip Launch",
    category: "robotics",
    weight: 0.04,
    status: "upcoming",
    expected: "2027",
    likelihood: 0.46,
    updated: "Apr 24, 2026",
    description: [
      "✅ Apr 24, 2026: Samsung Taylor Texas fab (2nm) equipment installation ceremony CONFIRMED LIVE — CEO Han Jin-man in attendance; AI5 + AI6 manufacturing ramp officially underway; 2nm yields in high-50% range; volume production targeting 2027 (evxl.co / Korea Herald)",
      "🆕 Apr 20, 2026: Samsung Taylor Texas fab (2nm) kicks off equipment installation ceremony April 24 — CEO Han Jin-man attending; AI5 + AI6 manufacturing milestone lands 3.5 years after groundbreaking; 2nm yields now in high-50% range (60% = stable mass production threshold); $16.5B Tesla deal signed Jul 2025 unblocked the ramp; volume production targeting 2027 (evxl.co / Chosun Daily / Korea Herald)",
      "🆕 Apr 17, 2026: AI6 tapeout officially targeted for December 2026 — Musk announces AI5→AI6→AI7 chip roadmap; AI6 slated for next-gen Optimus and Terafab supercomputer clusters; accelerating cadence signals Tesla is now a serious silicon company, not just an EV maker",
      "🆕 Apr 17, 2026: AI5 confirmed to deliver ~5x compute performance over current AI4 chip — Musk stated AI5 'makes the cars almost perfect and greatly enhances Optimus capabilities'; engineering samples at Samsung Korea underway; volume production 2027",
      "🆕 Apr 16, 2026: Electrek reports AI5 is nearly 2 years behind original schedule (was promised for 2024 vehicles); tape-out Apr 15 confirms the design is done, but engineering samples + volume production targets 2027 — AI5 in vehicles is now a late-2027/2028 event",
      "🆕 Apr 15, 2026: Musk clarified on X that AI5 is NOT going into vehicles — 'AI4 is enough to achieve much better than human safety for FSD.' AI5 is targeted at Optimus robots and supercomputer clusters. In-vehicle chip upgrade (AI4.5 or future HW5) timeline pushed to 2027+.",
      "Cybercab confirmed launching on AI4 hardware — no HW5 dependency for near-term robotaxi scale",
      "🚨 Apr 23, 2026 (10-Q filing): Tesla acquiring an AI hardware company for up to $2B in Tesla stock + equity awards — $1.8B contingent on successful deployment of acquired technology. Company unnamed. Likely inference hardware, custom silicon, or robotics compute stack. If deployed into Optimus/FSD, this could meaningfully accelerate AI5+ timeline or fill a gap in the current chip roadmap.",
      "✅ Apr 22, 2026 (Q1 deck): Tesla confirmed 'completed the final chip design of AI5 inference processor' in April — tape-out official. Tesla Research Fab now on Giga Texas campus. SpaceX partnership to build largest chip fab ever: logic + memory + packaging vertically integrated.",
      "AI5 taped out Apr 15, 2026 — manufacturing dual-sourced at TSMC Arizona and Samsung Texas; engineering samples late 2026, volume production 2027",
      "HW5/AI5 for vehicles is now a 2027 story at earliest — reduces near-term catalyst weight",
      "HW4 currently deployed — significant improvement over HW3; Musk says sufficient for FSD safety targets",
      "Tesla designs chips in-house (vs buying from Nvidia/Qualcomm) — huge margin advantage when it ships",
    ]
  },
  {
    id: "ai_inference",
    label: "AI Inference Revenue",
    category: "robotics",
    weight: 0.03,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.30,
    updated: "Mar 22, 2026",
    description: [
      "🚨 Apr 23, 2026 (10-Q): Tesla acquiring AI hardware company for up to $2B (stock + equity awards) — $1.8B contingent on deployment milestones. If it\'s inference/edge compute hardware, this directly accelerates the AI inference revenue thesis.",
      "Tesla monetizing AI compute infrastructure as a service to third parties",
      "Dojo + HW5 infrastructure could be offered as cloud AI training/inference",
      "Early stage — no public product or pricing announced",
      "Precedent: AWS started as internal infrastructure, became Amazon's biggest profit driver",
      "Near-term probability low — Tesla focus is internal FSD/Optimus training",
      "Long-term: if realized, could rival energy division as a margin driver",
    ]
  },

  // FINANCIALS
  {
    id: "q1_earnings",
    label: "Q1 2026 Earnings Beat",
    category: "financials",
    weight: 0.08,
    status: "complete",
    expected: "Q1 2026",
    likelihood: 1.0,
    updated: "Apr 22, 2026",
    description: [
      "✅ Apr 22, 2026 — OFFICIAL SHAREHOLDER DECK: Revenue $22.387B (+16% YoY). Non-GAAP EPS $0.41 (+52% YoY). GAAP EPS $0.13 (+8% YoY). GAAP gross margin 21.1% (+478 bps YoY from 16.3%). Operating income $941M (+136% YoY). Operating margin 4.2% (+214 bps YoY). Adj EBITDA $3.668B (+30%). Op cash flow $3.937B (+83% YoY). Free cash flow $1.444B (+117% YoY). Cash $44.743B (+21% YoY). TSLA +4% AH.",
      "⚠️ Apr 22, 2026: Energy revenue $2.408B (–12% YoY) — confirmed miss. Services +42% YoY ($3.745B) — standout outperformer. CapEx $2.493B (+67% YoY) — heavy investment cycle ongoing.",
      "✅ Apr 22, 2026 (Operations highlights): FSD Supervised approved Netherlands. Launched unsupervised Robotaxi Dallas + Houston. Began ramping lithium, cathode, LFP production. Prepared lines for Megapack 3, Cybercab, Tesla Semi. Cortex 2 online + training. Dojo 3 in development.",
      "✅ Apr 22, 2026: Optimus — Fremont converting Model S/X lines to Optimus (Q2). Giga Texas 2nd-gen line prep underway, 10M robot/yr long-term capacity. Demand rebound confirmed in APAC, South America, EMEA, North America.",
      "⚠️ Apr 22, 2026 (YoY summary): Profitability drivers itemized — one-time warranty + tariff benefits listed FIRST. Structural positive: lower avg cost/vehicle due to lower material costs. Lower regulatory credits = headwind (cited twice). CEO 2025 SBC + AI/R&D opex = headwinds. Tesla invested $2.0B in SpaceX equity in Q1.",
      "🚨 Deliveries: 358,023 (missed 365,600 consensus). Production: 408,386 — 50,363 units into inventory.",
    ]
  },
  {
    id: "delivery_rebound",
    label: "Delivery Volume Rebound",
    category: "financials",
    weight: 0.07,
    status: "upcoming",
    expected: "Q2 2026",
    likelihood: 0.38,
    updated: "Apr 22, 2026",
    description: [
      "⚠️ Apr 22, 2026 (Q1 deck): Inventory 27 days of supply (+23% YoY). Cumulative all-time: 9.2M. Model YL rolling out globally. Demand rebound in APAC, South America, EMEA, North America.",
      "2025 deliveries: 1.63M — down 8.5% YoY",
      "⚠️ Q1 2026: 358,023 delivered — missed consensus by 7,600; YoY +6.3% but vs a sandbagged quarter (Model Y retool shutdown); not a true rebound",
      "⚠️ 50,363 more vehicles produced than delivered in Q1 — sustained inventory build across multiple quarters signals structural demand softness, not logistics timing",
      "Refreshed Model Y (Juniper) launched Q1 2026 — didn't drive the volume beat analysts expected",
      "$25K affordable model needed to expand TAM beyond current demographics",
      "Cybercab adds new delivery category from Q2 2026 — not directly comparable to auto deliveries",
      "BYD, SAIC, Geely intensifying competition in key markets (Europe, China)",
      "Brand recovery essential — Musk DOGE involvement correlated with demand drop in key markets",
      "Tesla cash reserves: $44.1B end of 2025 (+21% YoY) — war chest intact for incentives",
      "Target: return to 2M+ deliveries in 2026 — Q1 pace of 358K × 4 = ~1.43M run rate; well below target",
    ]
  },
  {
    id: "margin_recovery",
    label: "Gross Margin >20%",
    category: "financials",
    weight: 0.05,
    status: "active",
    expected: "Q2 2026",
    likelihood: 0.74,
    updated: "Apr 22, 2026",
    description: [
      "✅ Apr 22, 2026: Q1 2026 gross margin confirmed 21.1% — up 478 bps YoY from 16.3%, above Q4 2025's 20.1%. Now two consecutive quarters above 20%. Strongest gross margin print in years.",
      "⚠️ Apr 22, 2026: Q1 margin partly supported by one-time warranty + tariff-related adjustments — some uplift non-recurring. Q2 sustainability test ahead.",
      "Q4 2025: 20.1% consolidated gross margin — two-year high at the time",
      "Q4 2025 auto gross margin (ex-credits): 17.7% — recovering from 15.4% low",
      "Key drivers: supply chain optimization, unboxed manufacturing, energy mix, robotaxi ramp (near 100% margin)",
      "Target: sustain >20% gross margin consistently through 2026",
      "Risk: global EV price war ongoing — BYD discounting pressuring Tesla pricing",
      "⚠️ Apr 22, 2026 (earnings call): Tesla raised 2026 capex guidance to $25B, up from prior $20B plan (+25%). Analysts flagged concern. Covers: Optimus line installs (Fremont + Texas), Cortex AI compute expansion, Megapack 3 factory (Houston + Texas), Cybercab ramp, Semi production, lithium refinery, semiconductor fab (AI5/AI6). FCF will be squeezed until these lines generate revenue.",
    ]
  },
  {
    id: "energy_revenue",
    label: "Energy Revenue >$10B",
    category: "financials",
    weight: 0.04,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.50,
    updated: "Apr 22, 2026",
    description: [
      "⚠️ Apr 22, 2026 (official Q1 deck): Energy revenue $2.408B in Q1 — down 12% YoY from $2.730B in Q1 2025. Annualized Q1 pace = ~$9.6B (below $10B threshold). No Q2 guidance. Recovery required across Q2–Q4 to hit full-year targets.",
      "2025 full-year energy revenue: $12.8B (+30% YoY) — already exceeded $10B, but 2026 on weaker footing",
      "Megapack 3 production lines being prepared — potential H2 2026 volume ramp catalyst",
      "Megapack backlog: 2–3 year waitlist — demand intact, execution and timing uncertain",
      "Powerwall 3 ramp adds residential recurring revenue",
      "2026 target: $16B+ requires strong Q2–Q4; currently behind pace",
    ]
  },
  {
    id: "insurance_profit",
    label: "Tesla Insurance Profitable",
    category: "financials",
    weight: 0.03,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.40,
    updated: "Mar 22, 2026",
    description: [
      "Tesla Insurance uses real-time driving data (Safety Score) for dynamic pricing",
      "Currently available in ~12 US states — expansion ongoing",
      "Not yet available to existing owners in Florida (tracked separately)",
      "Competitive advantage: Tesla has granular data competitors cannot access",
      "Potential for 80–90% loss ratio improvement vs industry average with better data",
      "Reaching profitability would signal actuarial model is working",
      "Long-term: insurance becomes high-margin recurring revenue attached to every vehicle",
      "Risk: insurance losses have historically been unpredictable even with better data",
    ]
  },
  {
    id: "share_buyback",
    label: "Share Buyback Program",
    category: "financials",
    weight: 0.02,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.35,
    updated: "Mar 22, 2026",
    description: [
      "Tesla has $44.1B cash on hand — no buyback program announced yet",
      "Musk has historically preferred reinvestment over buybacks",
      "A buyback would signal confidence that growth CapEx needs are fully funded",
      "Sentiment catalyst: buybacks typically boost EPS and indicate management conviction",
      "Low near-term probability — CapEx demands ($20B+ in 2026) likely take priority",
      "Could be announced if robotaxi cash flows materialize faster than expected",
    ]
  },

  // PRODUCT
  {
    id: "model_y_refresh",
    label: "New Model Y Global Ramp",
    category: "product",
    weight: 0.06,
    status: "achieved",
    expected: "Q1 2026",
    likelihood: 0.88,
    updated: "Apr 2, 2026",
    description: [
      "Refreshed Model Y (Juniper) launched globally Q1 2026 — ✅ achieved",
      "Interior completely redesigned — ambient lighting, new center console, rear screen",
      "Improved range and efficiency on all variants",
      "⚠️ Q1 2026 delivery miss despite full Juniper availability — demand uplift not as strong as expected; 50K inventory build suggests supply outpacing demand",
      "Europe early signals positive (France +3x, Nordics +2x), but insufficient to lift overall numbers",
      "Critical for reversing two-year delivery decline — Q2 2026 will show whether Juniper drives real acceleration",
      "Production ramped at Giga Shanghai, Texas, Berlin",
    ]
  },
  {
    id: "semi_production",
    label: "Tesla Semi Production Ramp",
    category: "product",
    weight: 0.04,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.72,
    updated: "Apr 22, 2026",
    description: [
      "✅ Apr 22, 2026 (Q1 Outlook): Tesla OFFICIAL: 'Cybercab, Tesla Semi and Megapack 3 are on schedule for volume production starting in 2026.' Explicit commitment in Outlook section.",
      "✅ Apr 22, 2026 (Q1 manufacturing table): Tesla Semi = 'Pilot Production' at Gigafactory Nevada.",
      "Semi production line confirmed at Gigafactory Nevada",
      "Pepsi pilot fleet has logged significant miles — positive reliability data",
      "500-mile range on single charge — no Class 8 competitor matches this",
      "Production target: ramp toward 50K units/yr at full scale",
      "Economics: $0.08–$0.10/mile operating cost vs $0.38/mile diesel",
      "Reservation list: hundreds of enterprise fleets on waitlist",
      "Key risk: 4680 cell supply chain must scale in parallel",
    ]
  },
  {
    id: "affordable_model",
    label: "$25K Affordable Model",
    category: "product",
    weight: 0.05,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.48,
    updated: "Apr 10, 2026",
    description: [
      "🆕 Apr 10, 2026: Reuters confirmed Tesla is actively developing a new smaller, cheaper EV — sources say production could start within months; positions Tesla below $30K price point alongside Cybercab sub-$30K target.",
      "Sub-$25K Tesla model critical for TAM expansion beyond current demographics",
      "Relies on 4680 cell cost reduction reaching target ($60/kWh structural pack)",
      "Unboxed manufacturing process designed to slash assembly costs",
      "No official unveil date confirmed — Q4 2026 is speculative",
      "At $25K, Tesla would be price-competitive with ICE vehicles globally",
      "Could add 500K–1M incremental deliveries/yr if successful",
      "Risk: Musk has teased affordable model multiple times — execution track record mixed",
    ]
  },
  {
    id: "cybertruck_profit",
    label: "Cybertruck Profitable",
    category: "product",
    weight: 0.03,
    status: "upcoming",
    expected: "Q2 2026",
    likelihood: 0.45,
    updated: "Apr 16, 2026",
    description: [
      "🆕 Apr 20, 2026: Teslarati confirms ~1 in 5 Cybertruck Q1 2026 registrations were transferred internally within Musk's companies (SpaceX purchases) — quantifies the organic demand hole; civilian retail demand weaker than headline numbers suggest; bear case on Cybertruck profitability strengthened",
      "🆕 Apr 16, 2026: Electrek reveals SpaceX purchased 1,279 Cybertruck units — inflating reported sales figures; raises serious questions about organic retail demand; if SpaceX is propping up Cybertruck numbers, underlying civilian demand may be materially weaker than reported; bear case strengthened",
      "Cybertruck production ramping at Giga Texas — initial units unprofitable",
      "Complex stainless steel body and new 48V architecture drove early cost overruns",
      "Q4 2025: Tesla indicated Cybertruck approaching positive gross margin",
      "Hitting profitability would validate the platform and enable volume expansion",
      "Current annual production rate: ~40K units — far below original projections",
      "Risk: niche product — US pickup truck buyers skew conservative, slow EV adoption",
    ]
  },
  {
    id: "roadster_reveal",
    label: "New Roadster Launch",
    category: "product",
    weight: 0.02,
    status: "upcoming",
    expected: "Q2–Q3 2026",
    likelihood: 0.24,
    updated: "Apr 23, 2026",
    description: [
      "🆕 Apr 23, 2026: Musk on Q1 earnings call — 'may be able to debut new Roadster in a month or so' (TipRanks/CNBC); first timeline signal in years; unexpected acceleration from '2027' to possible May/June 2026 reveal; unveil ≠ production start, but marks an inflection in public attention on the Roadster program",
      "⚠️ Apr 22, 2026 (Q1 manufacturing table): Roadster = 'Design development' at TBD location — furthest from production of all Tesla products. No site, no timeline.",
      "Original Roadster reservation deposits paid ~2017 — nearly a decade of delays",
      "Expected specs: 0–60 in under 1.9 sec, 620-mile range, SpaceX cold gas thruster package",
      "Halo product — brand prestige, not volume. 2027+ delivery more likely.",
    ]
  },

  // MANUFACTURING
  {
    id: "battery_4680",
    label: "4680 Cell Mass Production",
    category: "manufacturing",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.65,
    updated: "Mar 22, 2026",
    description: [
      "✅ Apr 22, 2026 (Q1 deck): 4680 at Giga Texas = 40 GWh installed annual capacity — Production status. LFP cells in Nevada = 7 GWh Early Ramp. Cathode Materials Texas = 10 GWh Early Ramp. Battery pack capacity remains the limiting factor for vehicle production ramp.",
      "4680 structural battery cells: tabless design, higher energy density, lower cost target",
      "Production at Giga Texas ramping — still below cost targets as of Q4 2025",
      "Target: $60/kWh structural pack cost — would enable $25K vehicle and Cybercab economics",
      "Key enabler for: affordable model, Cybercab unit economics, Semi profitability",
      "Current yield rates improving but not yet at mass-production efficiency",
      "Tesla also sourcing 2170 cells from Panasonic/CATL as hedge",
      "Risk: chemistry and manufacturing complexity has caused multiple timeline slips",
    ]
  },
  {
    id: "giga_mexico",
    label: "Gigafactory Mexico Groundbreak",
    category: "manufacturing",
    weight: 0.04,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.40,
    updated: "Mar 22, 2026",
    description: [
      "Gigafactory Monterrey, Mexico announced — land purchased, permits filed",
      "Designed for affordable model production targeting North American market",
      "Proximity to US border reduces logistics costs vs China imports",
      "Qualifies for IRA EV tax credits (North American final assembly requirement)",
      "Construction reportedly paused in 2025 pending US tariff clarity",
      "Resumption of groundbreaking would be a strong volume signal for 2027–2028",
      "Risk: US–Mexico tariff uncertainty under Trump administration",
    ]
  },
  {
    id: "unboxed_process",
    label: "Unboxed Manufacturing Live",
    category: "manufacturing",
    weight: 0.04,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.55,
    updated: "Mar 22, 2026",
    description: [
      "Revolutionary assembly method: vehicle built in sections simultaneously, not on linear line",
      "Reduces factory footprint by ~40% vs traditional auto manufacturing",
      "Eliminates massive stamping presses — lower tooling cost for new models",
      "Key enabler for Cybercab cost target and affordable model",
      "Currently in deployment at Giga Texas for Cybercab production line",
      "If successful: cuts manufacturing cost per vehicle by estimated 50%+",
      "Risk: unproven at scale — first full implementation; complexity could delay ramp",
    ]
  },

  {
    id: "lithium_refinery",
    label: "Lithium Refinery TX",
    category: "manufacturing",
    weight: 0.03,
    status: "active",
    expected: "2026",
    likelihood: 0.85,
    updated: "Apr 22, 2026",
    description: [
      "⚠️ Apr 22, 2026: Independent lab testing finds Tesla's TX refinery discharge contains hexavalent chromium (0.0104 mg/L) and arsenic (0.0025+ mg/L) — both absent from TCEQ-issued permit (Feb 2026 inspection didn't check heavy metals); local drainage district issued cease & desist; wastewater flows into Petronila Creek → Baffin Bay (major fishing area); Musk had called the facility 'very clean' (Benzinga)",
      "⚠️ Apr 22, 2026 (Q1 manufacturing table): Lithium Refining listed at 30 GWh capacity in Texas — 'Early Ramp' status, not full production. Consistent with environmental compliance risk (cease & desist) during ramp.",
      "🆕 Apr 20, 2026: Tesla's Robstown, TX lithium refinery (near Corpus Christi) now operational — largest in North America",
      "Elon Musk confirmed on X: 'the largest Lithium refinery in America is now operational'",
      "Production started Jan 2026 — went from groundbreaking (2023) to full operation in under 3 years",
      "34% lower carbon footprint than traditional hard rock refineries; engineered to incorporate recycled battery material",
      "Directly reduces Tesla's exposure to volatile lithium spot prices and foreign supply chain dependencies",
      "Key enabler for 4680 cell cost targets, Cybercab economics, and Megapack margin expansion",
      "Strategic moat: no other US automaker controls its own lithium refining capacity at this scale",
    ]
  },

  // ENERGY
  {
    id: "megapack_growth",
    label: "Megapack Revenue Growth",
    category: "energy",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.68,
    updated: "Apr 22, 2026",
    description: [
      "⚠️ Apr 22, 2026 (Q1 shareholder deck): Energy generation and storage revenue $2.408B (–12% YoY from $2.730B in Q1 2025). Q1 miss confirmed — no recovery guidance provided. Megapack 3 production lines being prepared — bullish for H2 2026.",
      "⚠️ Q1 2026: 8.8 GWh deployed — missed 14.4 GWh consensus by 40%; down vs Q4 2025 record of 14.2 GWh",
      "Morgan Stanley (Apr 5, 2026): 'Far too early to call this a trend' — energy storage is inherently lumpy. Data center demand robust. Unit economics intact.",
      "Full year 2025 energy revenue: $12.8B — up ~30% YoY",
      "Megapack backlog: 2–3 year waitlist for large utility projects — demand intact, execution uncertain",
      "New Megafactory (Lathrop, CA) and Shanghai energy factory both ramping",
      "Utility-scale battery storage market growing 40–50%/yr globally; Tesla ~35% global market share",
      "Q2 2026 key test — recovery to 12+ GWh would signal Q1 was timing/supply, not trend",
      "🆕 Megapack 3 announced (Apr 7, 2026) — next-gen product; production lines now being prepared per Q1 deck",
    ]
  },
  {
    id: "supercharger_network",
    label: "Supercharger Expansion",
    category: "energy",
    weight: 0.03,
    status: "in_progress",
    expected: "ongoing",
    likelihood: 0.92,
    updated: "Apr 1, 2026",
    description: [
      "✅ Apr 22, 2026 (Q1 deck): 8,463 stations / 79,918 connectors (+19% YoY). Added 2,200+ net new stalls in Q1. V4 Supercharger cabinets (3x power density, 2x stalls vs V3) now produced at Giga New York. First public Megacharger deployed in Southern California. Japan service center doubling targeted.",
      "Musk confirmed Apr 1, 2026: Supercharger energy delivered growing exponentially — 2025 was record year, 2026 Q1 tracking above 2024 Q1 pace",
      "15,000+ Supercharger stations globally — largest fast-charging network",
      "NACS (Tesla plug) adopted as North American standard by Ford, GM, Rivian, others",
      "Non-Tesla vehicles now using Supercharger network — new revenue stream",
      "Revenue from network access becoming meaningful ($0.40–$0.60/kWh)",
      "Continued expansion in underserved markets: Southeast US, rural corridors, Europe",
      "Infrastructure moat: years of permitting and construction ahead for competitors",
      "Also serves as data collection for energy load balancing + VPP integration",
    ]
  },
  {
    id: "powerwall_ramp",
    label: "Powerwall 3 Ramp",
    category: "energy",
    weight: 0.02,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.75,
    updated: "Mar 22, 2026",
    description: [
      "Powerwall 3 launched with integrated inverter — simpler install, lower cost",
      "13.5 kWh capacity, up to 11.5 kW continuous power output",
      "Significant demand backlog — installers reporting 6–9 month wait times",
      "Key markets: CA, TX, FL (storm/grid resilience demand), AUS",
      "Pairs with solar and VPP grid programs for recurring software revenue",
      "Production constrained by 4680 cells and inverter supply chain",
      "ASP ~$9K installed — high-margin residential energy product",
    ]
  },
  {
    id: "virtual_powerplant",
    label: "Virtual Power Plant Scale",
    category: "energy",
    weight: 0.02,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.50,
    updated: "Mar 22, 2026",
    description: [
      "Tesla VPP: aggregates Powerwall/Megapack fleet to dispatch grid energy during peak demand",
      "Active programs: CA (PG&E), TX (ERCOT), AUS (NEM) — early revenue generating",
      "Tesla earns grid payments for dispatching stored energy during emergencies",
      "Software-driven, near-zero marginal cost — pure margin revenue",
      "Scale requires millions of Powerwalls enrolled — currently tens of thousands",
      "Long-term: VPP becomes a distributed utility, recurring high-margin revenue",
      "Regulatory complexity varies by state/country — expansion requires approvals",
    ]
  },

  // CORPORATE / BRAND
  {
    id: "brand_recovery",
    label: "Brand Sentiment Recovery",
    category: "corporate",
    weight: 0.04,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.61,
    updated: "Apr 22, 2026",
    description: [
      "⚠️ Apr 22, 2026: Independent lab finds hexavalent chromium + arsenic in TX lithium refinery discharge — cease & desist issued; environmental liability risk adds to ongoing anti-Musk brand headwinds",
      "🆕 Apr 20, 2026: Tesla opening first Estonia showroom April 24 at Ülemiste Center, Tallinn — Baltic states expansion; continues EU push post-brand-recovery",
      "🆕 Apr 19–20, 2026: Optimus robot appearing live at Tesla Boston Boylston Street showroom during Boston Marathon weekend — hundreds of thousands of spectators + international broadcast; zero ad spend PR at scale (Teslarati)",
      "🆕 Apr 16, 2026: Molotov cocktail hurled at Tesla New Orleans sales office — latest in string of anti-Tesla/Musk incidents; no arrests; ATF + NOPD investigating; brand risk escalating",
      "🆕 Apr 14, 2026 (PM): UBS upgraded TSLA from 'Sell' to 'Neutral' with $352 PT — removes the last major Sell rating from a bulge-bracket bank; signals analyst community view that downside risk is now priced in; stock rose ~3.8% on the day to ~$359",
      "🆕 Apr 14, 2026: Model 3 + Model Y were the #1 and #2 bestselling used EVs in Australia in March 2026 (AADA data) — used EV sales +138% MoM to 7,557 units; supply tightened 38% to just 28.6 days (vs 60–90 day avg); cost-conscious Australians shifting from petrol/diesel; signals strong residual value + global demand recovery beyond EU",
      "🆕 Apr 7, 2026: Germany registrations QUADRUPLE to 9,252 units in March — best March ever, +315% YoY, +307% MoM",
      "Germany Q1 2026 now highest quarterly sales in 2 years; March alone = 72% of Q1 total (surge pattern)",
      "UK +20% YoY in March (8,599 units); Norway +178%, Sweden +144%, Denmark +96% — broad EU recovery confirmed",
      "Q1 2026 Germany volume already 66% of full-year 2025 — pace is accelerating dramatically",
      "Apr 1, 2026: March registrations TRIPLE in France, DOUBLE in Nordic countries — first hard data of EU demand rebound",
      "Europe: Tesla new car registrations down 28% in 2025 — brand damage documented",
      "Musk DOGE/political involvement strongly correlated with demand drop in EU and blue US states",
      "Brand recovery requires: reduced Musk political visibility, product momentum, positive press",
      "Refreshed Model Y and Cybercab launch are key product catalysts for narrative reset",
      "Brand sentiment ≠ product quality — vehicles still receive top safety/satisfaction ratings",
    ]
  },
  {
    id: "terafab",
    label: "Terafab Chip Factory",
    category: "robotics",
    weight: 0.06,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.75,
    updated: "Apr 16, 2026",
    description: [
      "Announced by Elon Musk on March 21, 2026 — joint Tesla/SpaceX venture",
      "Goal: build a vertically integrated facility producing 1+ terawatt of AI compute per year",
      "Initial cost: $20B–$25B — NOT included in Tesla's 2026 CapEx guidance",
      "Two chip categories: AI5 inference chips (Tesla vehicles + Optimus) and D3 chips (orbital AI satellites)",
      "🆕 Apr 16, 2026: Electrek notes AI5 is nearly 2 years behind original schedule — but milestone validated; engineering samples at Samsung Korea underway; AI5 targets Optimus + supercomputer clusters, NOT vehicles in 2026",
      "🆕 Apr 15, 2026: AI5 chip officially TAPED OUT — Elon Musk confirmed on X (5.1M views); tape-out is the final design milestone before silicon manufacturing begins",
      "🆕 Apr 15, 2026: AI6 chip confirmed in development — Musk teased AI6, Dojo3 and 'other exciting chips' in same post; roadmap extends beyond AI5",
      "Small-batch AI5 production expected 2026 — full fab ramp 2027–2028",
      "Eliminates reliance on TSMC and Nvidia — near-100% vertical integration of AI stack",
      "Actively hiring as of March 26, 2026 (Business Insider confirmed)",
      "🆕 Apr 7, 2026: Intel confirmed joining Terafab — bringing ultra-high-performance chip design, fabrication, and packaging expertise at scale",
      "Intel partnership directly addresses the key execution risk: chip fab is notoriously difficult and Intel has decades of manufacturing know-how",
      "Risk: $25B is enormous capital commitment on top of existing $20B+ CapEx plan",
    ]
  },
  {
    id: "cortex2",
    label: "Cortex 2.0 Supercomputer",
    category: "robotics",
    weight: 0.05,
    status: "active",
    expected: "Q2 2026",
    likelihood: 0.95,
    updated: "Apr 22, 2026",
    description: [
      "✅ Apr 22, 2026 (Q1 deck): Cortex 2 = >130k H100e equivalent — Early Ramp. Cortex 1 = >100k H100e — Production. Combined >230k H100e+ at Giga Texas. Cortex 2 now online running training workloads. Tesla: 'We continue to ramp our onsite training infrastructure to ensure sufficient compute resources for the development of our AI products and services.'",
      "Cortex 2.0 is Tesla's next-generation AI training supercomputer at Giga Texas",
      "First 250MW phase activates April 2026 — full 500MW capacity expected mid-2026",
      "Successor to original Cortex cluster (100MW) — 5x compute power at full build",
      "Primary purpose: training FSD neural networks and Optimus robot models simultaneously",
      "500MW at full capacity = one of the largest AI compute clusters in the world",
      "Dojo 3 custom silicon also in development — next-gen successor to D1/D2 (confirmed Q1 earnings)",
    ]
  },
  {
    id: "digital_optimus",
    label: "Digital Optimus (Macrohard)",
    category: "robotics",
    weight: 0.05,
    status: "in_progress",
    expected: "Q4 2026",
    likelihood: 0.60,
    updated: "Apr 1, 2026",
    description: [
      "Joint Tesla + xAI project announced March 11, 2026 — nicknamed 'Macrohard' (jab at Microsoft)",
      "Pairs xAI's Grok LLM with a Tesla-developed AI agent for agentic task execution",
      "Musk on X: 'Grok is the master conductor/navigator... directing Digital Optimus, which is processing and actioning the past 5 seconds'",
      "Effectively a software-based Optimus brain — Grok reasons, Tesla agent executes physical tasks",
      "Part of Tesla's investment agreement with xAI — combines both companies' AI capabilities",
      "Business Insider (Mar 2026): some internal tension as xAI's Macrohard effort stalls while Tesla's version ramps",
      "If successful: transforms Optimus from a robot with pre-programmed tasks to a general-purpose AI agent",
      "Key unlock for: complex factory work, external customer deployments, consumer robotics",
      "Risk: multi-company coordination complexity; xAI and Tesla have different incentive structures",
    ]
  },
  // SPACEX MERGER
  {
    id: "spacex_merger",
    label: "SpaceX–Tesla Merger",
    category: "spacex",
    weight: 0.10,
    status: "in_progress",
    expected: "2027–2028",
    likelihood: 0.28,
    updated: "Apr 3, 2026",
    description: [
      "✅ Apr 22, 2026 (Q1 financial summary): Tesla made a $2.0B SpaceX equity investment in Q1 2026 — confirmed in cash flow reconciliation. This is a deliberate balance sheet allocation to SpaceX, not a passive conversion. Deepens Tesla-SpaceX financial integration significantly.",
      "Cross-Equity Inflection Point (Mar 2026): Tesla's $2B xAI investment converted to SpaceX shares after SpaceX acquired xAI — Tesla now holds a direct stake in SpaceX",
      "Regulatory filings in March 2026 formally linked the two companies financially — first official cross-entity equity bridge",
      "Musk's 'system-of-systems' vision: Tesla (energy/transport/robotics) + SpaceX (launch/connectivity/interplanetary) converge into a unified platform",
      "Starlink integration thesis: Tesla vehicles as premium Starlink endpoints — always-on high-bandwidth connectivity without cellular dependency",
      "Satellite V2 Mini mass production underway — Starlink at automotive-grade reliability and cost becomes plausible by 2026–2027",
      "Optimus + SpaceX: shared actuator/materials R&D; space-hardened components reduce cost curve for terrestrial robotics",
      "A formal merger or deep partnership would collapse the valuation discount between Tesla (public, volatile) and SpaceX (private, ~$350B latest round)",
      "Bull case: combined entity = largest vertically integrated tech/energy/transport/space company in history — TAM expands beyond any current Tesla model",
      "Bear case: regulatory, shareholder, and conflicts-of-interest barriers remain substantial; SpaceX shareholders resistant to public market exposure",
      "Near-term catalyst watch: any formal joint venture announcement, expanded Starlink Tesla integration, or SEC filings deepening cross-equity",
    ]
  },

  {
    id: "elon_focus",
    label: "Elon Returns Full Focus",
    category: "corporate",
    weight: 0.05,
    status: "upcoming",
    expected: "Q2 2026",
    likelihood: 0.53,
    updated: "Apr 27, 2026",
    description: [
      "🆕 Apr 27, 2026: Musk confirmed 8M sq-ft Optimus factory at Giga Texas; gave specific Optimus 3 production timeline (late July/Aug), Roadster reveal 'in a month or so,' and concrete multi-city robotaxi targets — most operationally engaged earnings call in years; Autoweek / notateslaapp confirm Tesla is clearly primary focus heading into Q2",
      "🆕 Apr 23, 2026: Musk led Tesla's Q1 earnings call with deep detail on Optimus, robotaxi, FSD, and Roadster — active operational engagement signals Tesla is clearly his primary focus heading into Q2; Roadster tease + Optimus unveil timing + 'dozen states' FSD target all originated from Musk directly on the call",
      "Musk's involvement with DOGE (Dept. of Government Efficiency) runs through ~May 2026",
      "Also managing: xAI, X (Twitter), SpaceX, Neuralink, The Boring Company",
      "Tesla investors have consistently expressed concern about time allocation",
      "Q4 2025 earnings call: Musk indicated DOGE role would wind down mid-2026",
      "Historical pattern: Musk refocus on Tesla (e.g., 2019 post-Boring Co) preceded strong execution",
      "Return of full attention = faster decision-making, better product cadence, investor confidence",
      "Sentiment catalyst: any public statement or action signaling Tesla prioritization",
    ]
  },
];

export const links = [
  // Autonomy chain
  { source: "fsd_v15", target: "fsd_unsupervised" },
  { source: "dojo_v2", target: "fsd_unsupervised" },
  { source: "fsd_unsupervised", target: "robotaxi_austin" },
  { source: "fsd_unsupervised", target: "cybercab_production" },
  { source: "regulatory_approval", target: "cybercab_production" },
  { source: "cybercab_production", target: "robotaxi_expansion" },
  { source: "robotaxi_austin", target: "robotaxi_app" },
  { source: "robotaxi_austin", target: "robotaxi_expansion" },
  { source: "regulatory_approval", target: "robotaxi_expansion" },
  { source: "fsd_unsupervised", target: "fsd_licensing" },
  // Robotics chain
  { source: "dojo_v2", target: "optimus_production" },
  { source: "hw5_chip", target: "optimus_production" },
  { source: "optimus_factory", target: "optimus_production" },
  { source: "optimus_production", target: "optimus_external" },
  { source: "dojo_v2", target: "ai_inference" },
  { source: "hw5_chip", target: "ai_inference" },
  // Financial chain
  { source: "delivery_rebound", target: "q1_earnings" },
  { source: "cybercab_production", target: "q1_earnings" },
  { source: "optimus_external", target: "q1_earnings" },
  { source: "delivery_rebound", target: "margin_recovery" },
  { source: "megapack_growth", target: "margin_recovery" },
  { source: "semi_production", target: "margin_recovery" },
  { source: "robotaxi_expansion", target: "margin_recovery" },
  { source: "margin_recovery", target: "share_buyback" },
  { source: "energy_revenue", target: "margin_recovery" },
  { source: "megapack_growth", target: "energy_revenue" },
  { source: "powerwall_ramp", target: "energy_revenue" },
  // Product chain
  { source: "model_y_refresh", target: "delivery_rebound" },
  { source: "affordable_model", target: "delivery_rebound" },
  { source: "cybertruck_profit", target: "margin_recovery" },
  { source: "battery_4680", target: "affordable_model" },
  { source: "battery_4680", target: "cybertruck_profit" },
  { source: "unboxed_process", target: "cybercab_production" },
  { source: "giga_mexico", target: "delivery_rebound" },
  // Corporate chain
  { source: "elon_focus", target: "brand_recovery" },
  { source: "brand_recovery", target: "delivery_rebound" },
  { source: "elon_focus", target: "optimus_production" },
  { source: "fsd_licensing", target: "energy_revenue" },
  { source: "robotaxi_app", target: "robotaxi_expansion" },
  { source: "insurance_profit", target: "margin_recovery" },
  { source: "virtual_powerplant", target: "energy_revenue" },
  { source: "supercharger_network", target: "energy_revenue" },
  { source: "supercharger_network", target: "delivery_rebound" },
  { source: "roadster_reveal", target: "brand_recovery" },
  { source: "roadster_reveal", target: "delivery_rebound" },
  // New 2026 catalysts
  { source: "terafab", target: "hw5_chip" },
  { source: "terafab", target: "ai_inference" },
  { source: "terafab", target: "dojo_v2" },
  { source: "cortex2", target: "fsd_unsupervised" },
  { source: "cortex2", target: "optimus_production" },
  { source: "digital_optimus", target: "optimus_production" },
  { source: "digital_optimus", target: "optimus_external" },
  { source: "elon_focus", target: "digital_optimus" },
  // Lithium refinery chain
  { source: "lithium_refinery", target: "battery_4680" },
  { source: "lithium_refinery", target: "megapack_growth" },
  { source: "lithium_refinery", target: "energy_revenue" },
  { source: "lithium_refinery", target: "affordable_model" },
  { source: "lithium_refinery", target: "margin_recovery" },
  { source: "battery_4680", target: "lithium_refinery" },
  // SpaceX merger chain
  { source: "elon_focus", target: "spacex_merger" },
  { source: "spacex_merger", target: "optimus_external" },
  { source: "spacex_merger", target: "digital_optimus" },
  { source: "spacex_merger", target: "ai_inference" },
];
