export const catalysts = [
  // AUTONOMY
  {
    id: "cybercab_production",
    label: "Cybercab Production Start",
    category: "autonomy",
    weight: 0.15,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.75,
    updated: "Apr 4, 2026",
    description: [
      "🚀 MASS PRODUCTION STARTED: Cybercab formally entered production at Giga Texas in April 2026 — first unit rolled off in February; now targeting several hundred units/week ramp",
      "Model S and Model X production officially ended — Fremont factory space now freed for Optimus; Giga Texas pivoting Cybercab + Optimus focus",
      "Eliminates steering wheel and pedals — purpose-built for autonomy",
      "Manufacturing cost target: $40K–$45K/unit (vs Waymo's ~$200K)",
      "New charge port and improved FSD cameras confirmed in first impressions (Mar 22)",
      "Wheelchair-height seats; ambient lighting; refined interior",
      "TSMC hardware batches in early validation as of March 2026",
      "Unboxed manufacturing process being deployed for Cybercab line",
      "Morgan Stanley (Mar 18, 2026): officially classified Tesla as AI platform company, Cybercab as core catalyst",
      "⚠️ RISK (Apr 2026): 3 Cybercab team leaders departed within weeks — program manager, ride-hailing infrastructure director, AND assembly leader all gone; FSD reliability concerns cited",
    ]
  },
  {
    id: "robotaxi_austin",
    label: "Robotaxi Launch Austin",
    category: "autonomy",
    weight: 0.12,
    status: "achieved",
    expected: "Q2 2025",
    likelihood: 0.95,
    updated: "Apr 6, 2026",
    description: [
      "Morgan Stanley (Apr 5, 2026): 'Scaling the unsupervised robotaxi fleet is the most important catalyst for $TSLA this year' — each incremental mile accelerates FSD learning → higher attach rates → re-accelerates auto demand → improves FCF. Stock expected to trade in close correlation to robotaxi fleet scaling + 7-city expansion by end of June.",
      "LIVE — Austin fleet operational as of mid-2025",
      "44 vehicles observed last 30d | 9 unsupervised active | Bay Area: 457 total observed (+4 this week, supervised only) — source: robotaxitracker.com (Apr 6, 2026)",
      "🏁 Austin fleet total mileage: ~1.01M+ miles | current rate: ~4,700 mi/day",
      "Austin pricing: avg fare $5.12 | avg 3.7 mi/ride | 1,642 logged ride fares (+255 since Apr 5) | 62 riders community",
      "Coverage area: 244 sq mi — majority supervised; unsupervised pilot expanded into downtown (crossed Colorado River, Mar 31)",
      "Bay Area: 453 vehicles deployed, 1,094 sq mi coverage — human-driver supervised ride hail only; awaiting CA regulatory approval",
      "MAJOR (Mar 31): Unsupervised geofence more than doubled — now covers downtown Austin north of Colorado River",
      "FSD update 2026.8.6 rolling out globally Apr 3 — hints at FSD v14 imminent Europe launch ahead of Apr 10 RDW approval date",
      "Min ride age lowered to 8 years old (with adult present) — expanding consumer access",
      "NHTSA: 28 all-time ADS incident reports, 10 in last 90 days",
    ]
  },
  {
    id: "fsd_unsupervised",
    label: "FSD Unsupervised Rollout",
    category: "autonomy",
    weight: 0.10,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.73,
    updated: "Apr 1, 2026",
    description: [
      "FSD v14.3 broad rollout underway — update 2026.8.6 rolling out Apr 3–4 globally; hints at FSD v14 imminent European launch",
      "Austin: unsupervised pilot active — ongoing driverless rides logged weekly",
      "Bay Area: 449 vehicles deployed but supervised-only — awaiting CA regulatory approval",
      "FSD v14.2.2.5 rolled out via OTA in March 2026; v14.3 now in broad rollout; 2026.8.6 is pre-launch prep for EU",
      "⚠️ DISCLOSURE (Apr 3): Tesla confirmed in Senate letter that human operators can take direct remote control of robotaxis in rare cases (at ≤2 mph, up to 10 mph) — only AV company to admit direct teleoperation; Waymo and others use advisory-only remote assist",
      "FSD v14 won MotorTrend 2026 Driver Assistance System of the Year",
      "Cumulative FSD miles: 8.4 billion — 42x Waymo's ~200M fully driverless miles",
      "1.1 million FSD subscribers as of Q1 2026 | $99–$199/mo subscription",
      "🇳🇱 Netherlands RDW approval date: April 10, 2026 — 6 days away; 2026.8.6 update = EU FSD launch prep confirmed",
      "Risk: NHTSA has not yet granted 'fully autonomous' commercial approval",
    ]
  },
  {
    id: "robotaxi_expansion",
    label: "Robotaxi Multi-City",
    category: "autonomy",
    weight: 0.08,
    status: "upcoming",
    expected: "1H 2026",
    likelihood: 0.60,
    updated: "Apr 1, 2026",
    description: [
      "Las Vegas, Dallas, Houston, Miami, Orlando, Phoenix, Tampa all listed as '1H 2026' on robotaxitracker.com city map (confirmed Apr 3)",
      "Bay Area (CA): 449 vehicles active — human-driver only, 1,094 sq mi coverage",
      "36 Cybercabs spotted across 7 regions (27 test fleet active in Austin) as of Apr 6, 2026",
      "Planned 1H 2026 expansion: Dallas TX, Houston TX, Las Vegas NV",
      "Planned 1H 2026 expansion: Miami FL, Orlando FL, Phoenix AZ, Tampa FL",
      "Evidence emerging of imminent Las Vegas and Dallas launches (notateslaapp.com, Mar 31)",
      "Austin unsupervised geofence 2x+ expansion (crossed river into downtown) validates confidence for multi-city",
      "Q4 2025 earnings call: '25–50% of US with fully autonomous vehicles by end of 2026'",
      "BofA SOTP: Robotaxi business valued at ~$750B — ~52% of Tesla's total market cap at scale",
      "Key risk: CA regulatory approval needed before Bay Area fleet can go unsupervised",
      "Key risk: NHTSA federal approval still pending for commercial AV operation",
    ]
  },
  {
    id: "robotaxi_app",
    label: "Robotaxi Public App Launch",
    category: "autonomy",
    weight: 0.06,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.55,
    updated: "Mar 22, 2026",
    description: [
      "Consumer-facing Tesla Robotaxi app for public ride booking",
      "Currently ride access is invite-only / limited beta in Austin",
      "App launch would signal readiness for mass-market commercial operation",
      "Key unlock for network effects — more rides = more training data = better FSD",
      "Likely tied to multi-city expansion timeline in 1H–2H 2026",
      "Uber/Lyft competitive threat if Tesla opens app broadly — or potential partnership",
      "📱 App v26.3.0 (Apr 3, 2026): Apple Pay + Google Pay support added — Android app assets suggest broad platform launch imminent; map UI redesign underway",
    ]
  },
  {
    id: "fsd_v13",
    label: "FSD v13 Release",
    category: "autonomy",
    weight: 0.05,
    status: "achieved",
    expected: "Q1 2026",
    likelihood: 0.95,
    updated: "Mar 22, 2026",
    description: [
      "FSD v13 released — major capability leap over v12",
      "End-to-end neural network architecture fully matured",
      "Dramatically reduced intervention rates vs prior versions",
      "Foundation for v14 (current) and unsupervised operation",
      "Enabled unsupervised pilot program in Austin to begin",
      "MotorTrend 2026 Driver Assistance System of the Year awarded to FSD v14 (successor)",
    ]
  },
  {
    id: "fsd_licensing",
    label: "FSD Licensed to OEMs",
    category: "autonomy",
    weight: 0.07,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.30,
    updated: "Mar 22, 2026",
    description: [
      "Tesla licensing FSD software stack to other automakers",
      "Near 100% gross margin revenue — no hardware cost to Tesla",
      "Musk has confirmed discussions with 'several' OEMs",
      "No public deal announced as of March 2026",
      "Would transform Tesla into an AI software licensor — massive TAM expansion",
      "Risk: OEMs may prefer developing in-house or using Waymo/Mobileye alternatives",
      "If even one major OEM deal closes, this is a significant re-rating catalyst",
    ]
  },
  {
    id: "regulatory_approval",
    label: "Federal AV Regulatory Approval",
    category: "autonomy",
    weight: 0.08,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.40,
    updated: "Mar 31, 2026",
    description: [
      "NHTSA federal framework needed for commercial autonomous operation at scale",
      "Currently Tesla operates under state-level exemptions (TX, CA)",
      "Netherlands RDW approval (Europe): hard date April 10, 2026",
      "NHTSA SGO 2021-01 ADS reporting active — Tesla has 28 all-time incident reports",
      "10 incidents reported in last 90 days — most property damage, no fatalities",
      "GLJ Research flagged: Tesla accident frequency still above human driving baseline",
      "Federal approval would unlock all 50 states simultaneously — enormous scale catalyst",
      "Risk: political/lobbying environment uncertain; timeline could slip to 2027",
    ]
  },

  // ROBOTICS / AI
  {
    id: "optimus_production",
    label: "Optimus Mass Production",
    category: "robotics",
    weight: 0.12,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.60,
    updated: "Apr 1, 2026",
    description: [
      "Musk shared major Optimus Gen 3 production update — scaling confirmed beyond first line",
      "Model S and Model X production officially ends Q2 2026 (started Apr 1) — factory space freed for Optimus",
      "Optimus 4 targeted for Gigafactory Texas at higher volumes (2026–2027)",
      "Currently ~1,000 units/yr internal deployment pace — target is 10K+ by end 2026",
      "Musk long-term thesis: Optimus becomes 80% of Tesla's total value",
      "DELAY (Mar 31): Optimus Gen 3 unveil postponed — Musk says 'walking around but needs finishing touches' before showing; April reveal now expected",
      "Gen 3 nearing human form factor — significant dexterity improvements confirmed by Tesla engineers",
      "Cern Basher / InvestAnswers: enormous optionality but speculative near-term",
      "Key risk: fine motor skill reliability still unproven for complex manufacturing tasks",
      "Key risk: production ramp historically difficult — Cybertruck ramp as cautionary tale",
    ]
  },
  {
    id: "optimus_external",
    label: "Optimus External Sales",
    category: "robotics",
    weight: 0.08,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.35,
    updated: "Mar 22, 2026",
    description: [
      "First external customer deliveries of Optimus humanoid robot",
      "Target price not officially confirmed — estimated $20K–$30K/unit",
      "Initial customers likely industrial/warehouse clients, not consumers",
      "External sales would mark Tesla's entry into humanoid robotics market",
      "TAM: Morgan Stanley estimates global humanoid robot market at $6T by 2040",
      "Competition: Boston Dynamics, Figure AI, 1X, Apptronik all racing to scale",
      "InvestAnswers model: 100K external units/yr @ $20K margin = $2B/yr, growing exponentially",
    ]
  },
  {
    id: "optimus_factory",
    label: "Optimus In-Factory Deployment",
    category: "robotics",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.70,
    updated: "Mar 23, 2026",
    description: [
      "Optimus units currently working inside Tesla Gigafactories",
      "Tasks: battery cell handling, parts sorting, wiring harness assembly",
      "Proof-of-concept phase — each successful task expands scope",
      "Elon confirmed on Q4 2025 earnings call: 'Optimus doing useful work at Giga Texas'",
      "Internal deployment de-risks external sales — real-world validation at scale",
      "Cost savings from replacing human labor feeds back into production cost reduction",
    ]
  },
  {
    id: "dojo_v2",
    label: "Dojo Supercomputer Expansion",
    category: "robotics",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.70,
    updated: "Mar 22, 2026",
    description: [
      "Dojo: Tesla's custom AI training supercomputer built on D1 chips",
      "Designed to process massive video datasets from Tesla fleet (8.4B miles)",
      "Reduces reliance on Nvidia H100/H200 GPUs — significant cost reduction",
      "Dojo v2 expansion underway — exaFLOP-scale compute being added",
      "Training FSD and Optimus models simultaneously",
      "Morgan Stanley estimated Dojo could add $500B to Tesla's valuation at full scale",
      "Risk: Nvidia still dominant; Dojo timeline has slipped before",
    ]
  },
  {
    id: "hw5_chip",
    label: "HW5 AI Chip Launch",
    category: "robotics",
    weight: 0.04,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.45,
    updated: "Mar 22, 2026",
    description: [
      "Next-generation in-vehicle inference chip for FSD and Optimus",
      "HW4 currently deployed — significant improvement over HW3",
      "HW5 expected to enable on-device AI capabilities not possible with HW4",
      "Critical for fully unsupervised FSD at scale without cloud dependency",
      "Also targeted for Optimus brain — faster reaction times, better sensor fusion",
      "Tesla designs chips in-house (vs buying from Nvidia/Qualcomm) — huge margin advantage",
    ]
  },
  {
    id: "ai_inference",
    label: "AI Inference Revenue",
    category: "robotics",
    weight: 0.03,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.30,
    updated: "Mar 22, 2026",
    description: [
      "Tesla monetizing AI compute infrastructure as a service to third parties",
      "Dojo + HW5 infrastructure could be offered as cloud AI training/inference",
      "Early stage — no public product or pricing announced",
      "Precedent: AWS started as internal infrastructure, became Amazon's biggest profit driver",
      "Near-term probability low — Tesla focus is internal FSD/Optimus training",
      "Long-term: if realized, could rival energy division as a margin driver",
    ]
  },

  // FINANCIALS
  {
    id: "q1_earnings",
    label: "Q1 2026 Earnings Beat",
    category: "financials",
    weight: 0.08,
    status: "upcoming",
    expected: "Q2 2026",
    likelihood: 0.50,
    updated: "Apr 6, 2026",
    description: [
      "🚨 OFFICIAL Q1 2026 DELIVERY RESULTS (Apr 2, 2026): 358,023 delivered — MISSED consensus of 365,600 by ~7,600 (~2%)",
      "Production: 408,386 total — 50,363 more produced than delivered; largest single-quarter inventory build on record",
      "Model 3/Y: 394,611 produced / 341,893 delivered (gap of ~53K units into inventory)",
      "⚠️ Other Models (Cybertruck + S/X): 13,775 produced / 16,130 delivered — Tesla confirmed Apr 1: Model S/X production is now permanently over; ~600 units left globally",
      "⚠️ Energy storage: 8.8 GWh deployed — 39% MISS vs analyst consensus of 14.4 GWh; down 38% from Q4 2025 record of 14.2 GWh; down 15% YoY vs Q1 2025 (10.4 GWh)",
      "YoY deliveries: +6.3% — vs Q1 2025, which was Tesla's weakest quarter in years (Model Y lines shut for Juniper retool); beating a sandbagged quarter by 6% is not a rebound",
      "Sequential: -14.4% from Q4 2025 (418,227) — steeper than typical seasonal pattern",
      "Q1 2026 FINANCIAL earnings call: Wednesday, April 22, 2026 at 5:30 PM ET",
      "⚠️ TSLA -5% Apr 6, 2026 — shares tumbling on record inventory gap; EV tax credit expiry + rising auto loan delinquencies (5.2%) weighing on demand",
      "Barchart consensus (Apr 6): Q1 2026 EPS $0.24/share diluted (+60% YoY vs $0.15); analyst forecasting 1.6M deliveries for full year 2026 (Benzinga)",
      "Full year revenue consensus: $105B; gas tax holiday policy discussion putting EVs in focus",
      "Q4 2025 gross margin: 20.1% — two-year peak; auto gross margin recovered to 17.7%",
      "BYD delivered 2.257M BEVs in 2025 — now outsells Tesla globally",
      "Europe signals improving: France registrations tripled in March, Nordic countries doubled",
    ]
  },
  {
    id: "delivery_rebound",
    label: "Delivery Volume Rebound",
    category: "financials",
    weight: 0.07,
    status: "upcoming",
    expected: "Q2 2026",
    likelihood: 0.45,
    updated: "Apr 2, 2026",
    description: [
      "2025 deliveries: 1.63M — down 8.5% YoY, two consecutive years of decline",
      "⚠️ Q1 2026: 358,023 delivered — missed consensus by 7,600; YoY +6.3% but vs a sandbagged quarter (Model Y retool shutdown); not a true rebound",
      "⚠️ 50,363 more vehicles produced than delivered in Q1 — sustained inventory build across multiple quarters signals structural demand softness, not logistics timing",
      "Refreshed Model Y (Juniper) launched Q1 2026 — didn't drive the volume beat analysts expected",
      "$25K affordable model needed to expand TAM beyond current demographics",
      "Cybercab adds new delivery category from Q2 2026 — not directly comparable to auto deliveries",
      "BYD, SAIC, Geely intensifying competition in key markets (Europe, China)",
      "Brand recovery essential — Musk DOGE involvement correlated with demand drop in key markets",
      "Tesla cash reserves: $44.1B end of 2025 (+21% YoY) — war chest intact for incentives",
      "Target: return to 2M+ deliveries in 2026 — Q1 pace of 358K × 4 = ~1.43M run rate; well below target",
    ]
  },
  {
    id: "margin_recovery",
    label: "Gross Margin >20%",
    category: "financials",
    weight: 0.05,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.40,
    updated: "Apr 2, 2026",
    description: [
      "Q4 2025 auto gross margin (ex-credits): 17.7% — recovering from 15.4% low",
      "Consolidated gross margin Q4 2025: 20.1% — two-year high",
      "⚠️ Q1 2026 margin risk: 50K+ inventory build means incentives/discounts likely needed to clear stock — margin headwind",
      "⚠️ Energy segment miss (8.8 GWh vs 14.4 GWh consensus) removes a key margin-accretive contributor for Q1",
      "Key drivers: supply chain optimization, unboxed manufacturing, energy mix",
      "Target: sustain >20% gross margin consistently through 2026",
      "Risk: global EV price war ongoing — BYD discounting pressuring Tesla pricing",
      "CapEx 2026 expected to exceed $20B — requires strong margins to maintain FCF",
      "Regulatory credits ($ZEV) currently supplementing automotive margins",
      "Robotaxi revenue (near 100% margin) would structurally lift blended margins over time",
    ]
  },
  {
    id: "energy_revenue",
    label: "Energy Revenue >$10B",
    category: "financials",
    weight: 0.04,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.55,
    updated: "Apr 2, 2026",
    description: [
      "⚠️ Q1 2026: 8.8 GWh deployed — down 15% YoY vs Q1 2025 (10.4 GWh); well below Q4 2025 record of 14.2 GWh",
      "2025 full-year energy revenue: $12.8B — already exceeded $10B threshold, but 2026 pace at risk if Q1 trend holds",
      "YoY growth: ~30% in 2025 — fastest growing Tesla business unit; 2026 YoY now uncertain",
      "Megapack backlog remains long — suggests demand is intact; Q1 dip likely supply/timing-driven",
      "Powerwall 3 ramp adds residential recurring revenue stream",
      "Virtual Power Plant (VPP) programs expanding in CA, TX, AUS",
      "Energy gross margin improving — moving toward automotive-level margins",
      "2026 target: $16B+ revenue requires strong Q2–Q4 recovery after weak Q1",
      "April 22 earnings call will clarify whether Q1 was a blip or a trend reversal",
    ]
  },
  {
    id: "insurance_profit",
    label: "Tesla Insurance Profitable",
    category: "financials",
    weight: 0.03,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.40,
    updated: "Mar 22, 2026",
    description: [
      "Tesla Insurance uses real-time driving data (Safety Score) for dynamic pricing",
      "Currently available in ~12 US states — expansion ongoing",
      "Not yet available to existing owners in Florida (tracked separately)",
      "Competitive advantage: Tesla has granular data competitors cannot access",
      "Potential for 80–90% loss ratio improvement vs industry average with better data",
      "Reaching profitability would signal actuarial model is working",
      "Long-term: insurance becomes high-margin recurring revenue attached to every vehicle",
      "Risk: insurance losses have historically been unpredictable even with better data",
    ]
  },
  {
    id: "share_buyback",
    label: "Share Buyback Program",
    category: "financials",
    weight: 0.02,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.35,
    updated: "Mar 22, 2026",
    description: [
      "Tesla has $44.1B cash on hand — no buyback program announced yet",
      "Musk has historically preferred reinvestment over buybacks",
      "A buyback would signal confidence that growth CapEx needs are fully funded",
      "Sentiment catalyst: buybacks typically boost EPS and indicate management conviction",
      "Low near-term probability — CapEx demands ($20B+ in 2026) likely take priority",
      "Could be announced if robotaxi cash flows materialize faster than expected",
    ]
  },

  // PRODUCT
  {
    id: "model_y_refresh",
    label: "New Model Y Global Ramp",
    category: "product",
    weight: 0.06,
    status: "achieved",
    expected: "Q1 2026",
    likelihood: 0.88,
    updated: "Apr 2, 2026",
    description: [
      "Refreshed Model Y (Juniper) launched globally Q1 2026 — ✅ achieved",
      "Interior completely redesigned — ambient lighting, new center console, rear screen",
      "Improved range and efficiency on all variants",
      "⚠️ Q1 2026 delivery miss despite full Juniper availability — demand uplift not as strong as expected; 50K inventory build suggests supply outpacing demand",
      "Europe early signals positive (France +3x, Nordics +2x), but insufficient to lift overall numbers",
      "Critical for reversing two-year delivery decline — Q2 2026 will show whether Juniper drives real acceleration",
      "Production ramped at Giga Shanghai, Texas, Berlin",
    ]
  },
  {
    id: "semi_production",
    label: "Tesla Semi Production Ramp",
    category: "product",
    weight: 0.04,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.60,
    updated: "Mar 23, 2026",
    description: [
      "Semi production line confirmed at Gigafactory Nevada",
      "Pepsi pilot fleet has logged significant miles — positive reliability data",
      "500-mile range on single charge — no Class 8 competitor matches this",
      "Production target: ramp toward 50K units/yr at full scale",
      "Economics: $0.08–$0.10/mile operating cost vs $0.38/mile diesel",
      "Reservation list: hundreds of enterprise fleets on waitlist",
      "Key risk: 4680 cell supply chain must scale in parallel",
      "Key risk: production ramp timeline has slipped multiple times historically",
    ]
  },
  {
    id: "affordable_model",
    label: "$25K Affordable Model",
    category: "product",
    weight: 0.05,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.40,
    updated: "Mar 22, 2026",
    description: [
      "Sub-$25K Tesla model critical for TAM expansion beyond current demographics",
      "Relies on 4680 cell cost reduction reaching target ($60/kWh structural pack)",
      "Unboxed manufacturing process designed to slash assembly costs",
      "No official unveil date confirmed — Q4 2026 is speculative",
      "At $25K, Tesla would be price-competitive with ICE vehicles globally",
      "Could add 500K–1M incremental deliveries/yr if successful",
      "Risk: Musk has teased affordable model multiple times — execution track record mixed",
    ]
  },
  {
    id: "cybertruck_profit",
    label: "Cybertruck Profitable",
    category: "product",
    weight: 0.03,
    status: "upcoming",
    expected: "Q2 2026",
    likelihood: 0.50,
    updated: "Mar 22, 2026",
    description: [
      "Cybertruck production ramping at Giga Texas — initial units unprofitable",
      "Complex stainless steel body and new 48V architecture drove early cost overruns",
      "Q4 2025: Tesla indicated Cybertruck approaching positive gross margin",
      "Hitting profitability would validate the platform and enable volume expansion",
      "Current annual production rate: ~40K units — far below original projections",
      "Risk: niche product — US pickup truck buyers skew conservative, slow EV adoption",
    ]
  },
  {
    id: "roadster_reveal",
    label: "New Roadster Launch",
    category: "product",
    weight: 0.02,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.25,
    updated: "Mar 23, 2026",
    description: [
      "Unveil event pushed from April 1 to late April 2026 — Musk called it 'banger next level'",
      "Original Roadster reservation deposits paid ~2017 — nearly a decade of delays",
      "Expected specs: 0–60 in under 1.9 sec, 620-mile range, SpaceX cold gas thruster package",
      "Halo product — primary value is brand prestige, not volume",
      "Small contribution to revenue but significant marketing/media catalyst",
      "Low probability of meaningful 2026 production — more likely a 2027 delivery",
    ]
  },

  // MANUFACTURING
  {
    id: "battery_4680",
    label: "4680 Cell Mass Production",
    category: "manufacturing",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.65,
    updated: "Mar 22, 2026",
    description: [
      "4680 structural battery cells: tabless design, higher energy density, lower cost target",
      "Production at Giga Texas ramping — still below cost targets as of Q4 2025",
      "Target: $60/kWh structural pack cost — would enable $25K vehicle and Cybercab economics",
      "Key enabler for: affordable model, Cybercab unit economics, Semi profitability",
      "Current yield rates improving but not yet at mass-production efficiency",
      "Tesla also sourcing 2170 cells from Panasonic/CATL as hedge",
      "Risk: chemistry and manufacturing complexity has caused multiple timeline slips",
    ]
  },
  {
    id: "giga_mexico",
    label: "Gigafactory Mexico Groundbreak",
    category: "manufacturing",
    weight: 0.04,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.40,
    updated: "Mar 22, 2026",
    description: [
      "Gigafactory Monterrey, Mexico announced — land purchased, permits filed",
      "Designed for affordable model production targeting North American market",
      "Proximity to US border reduces logistics costs vs China imports",
      "Qualifies for IRA EV tax credits (North American final assembly requirement)",
      "Construction reportedly paused in 2025 pending US tariff clarity",
      "Resumption of groundbreaking would be a strong volume signal for 2027–2028",
      "Risk: US–Mexico tariff uncertainty under Trump administration",
    ]
  },
  {
    id: "unboxed_process",
    label: "Unboxed Manufacturing Live",
    category: "manufacturing",
    weight: 0.04,
    status: "in_progress",
    expected: "Q3 2026",
    likelihood: 0.55,
    updated: "Mar 22, 2026",
    description: [
      "Revolutionary assembly method: vehicle built in sections simultaneously, not on linear line",
      "Reduces factory footprint by ~40% vs traditional auto manufacturing",
      "Eliminates massive stamping presses — lower tooling cost for new models",
      "Key enabler for Cybercab cost target and affordable model",
      "Currently in deployment at Giga Texas for Cybercab production line",
      "If successful: cuts manufacturing cost per vehicle by estimated 50%+",
      "Risk: unproven at scale — first full implementation; complexity could delay ramp",
    ]
  },

  // ENERGY
  {
    id: "megapack_growth",
    label: "Megapack Revenue Growth",
    category: "energy",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.68,
    updated: "Apr 2, 2026",
    description: [
      "⚠️ Q1 2026: 8.8 GWh deployed — missed 14.4 GWh consensus by 40%; down vs Q4 2025 record of 14.2 GWh",
      "Morgan Stanley (Apr 5, 2026): 'Far too early to call this a trend' — energy storage is inherently lumpy due to permits, labor, interconnect approvals. Data center customer demand remains robust. Improving unit economics for utility-scale ESS intact.",
      "Q4 seasonality is typical (utilities frontload calendar-year projects), but YoY decline worth watching",
      "Full year 2025 energy revenue: $12.8B — up ~30% YoY",
      "Megapack backlog: 2–3 year waitlist for large utility projects — demand intact, execution uncertain",
      "New Megafactory (Lathrop, CA) and Shanghai energy factory both ramping — supply constraints may explain Q1 dip",
      "Gross margins improving — approaching 20%+ on energy segment",
      "Utility-scale battery storage market growing 40–50%/yr globally",
      "Tesla has ~35% global market share in utility-scale storage",
      "Essentially no competition at Megapack's price/performance level at scale",
      "Q2 2026 will be key — a recovery to 12+ GWh would signal Q1 was a timing/supply issue, not a trend",
    ]
  },
  {
    id: "supercharger_network",
    label: "Supercharger Expansion",
    category: "energy",
    weight: 0.03,
    status: "in_progress",
    expected: "ongoing",
    likelihood: 0.92,
    updated: "Apr 1, 2026",
    description: [
      "Musk confirmed Apr 1, 2026: Supercharger energy delivered growing exponentially — 2025 was record year, 2026 Q1 tracking above 2024 Q1 pace",
      "15,000+ Supercharger stations globally — largest fast-charging network",
      "NACS (Tesla plug) adopted as North American standard by Ford, GM, Rivian, others",
      "Non-Tesla vehicles now using Supercharger network — new revenue stream",
      "Revenue from network access becoming meaningful ($0.40–$0.60/kWh)",
      "Continued expansion in underserved markets: Southeast US, rural corridors, Europe",
      "Infrastructure moat: years of permitting and construction ahead for competitors",
      "Also serves as data collection for energy load balancing + VPP integration",
    ]
  },
  {
    id: "powerwall_ramp",
    label: "Powerwall 3 Ramp",
    category: "energy",
    weight: 0.02,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.75,
    updated: "Mar 22, 2026",
    description: [
      "Powerwall 3 launched with integrated inverter — simpler install, lower cost",
      "13.5 kWh capacity, up to 11.5 kW continuous power output",
      "Significant demand backlog — installers reporting 6–9 month wait times",
      "Key markets: CA, TX, FL (storm/grid resilience demand), AUS",
      "Pairs with solar and VPP grid programs for recurring software revenue",
      "Production constrained by 4680 cells and inverter supply chain",
      "ASP ~$9K installed — high-margin residential energy product",
    ]
  },
  {
    id: "virtual_powerplant",
    label: "Virtual Power Plant Scale",
    category: "energy",
    weight: 0.02,
    status: "upcoming",
    expected: "Q4 2026",
    likelihood: 0.50,
    updated: "Mar 22, 2026",
    description: [
      "Tesla VPP: aggregates Powerwall/Megapack fleet to dispatch grid energy during peak demand",
      "Active programs: CA (PG&E), TX (ERCOT), AUS (NEM) — early revenue generating",
      "Tesla earns grid payments for dispatching stored energy during emergencies",
      "Software-driven, near-zero marginal cost — pure margin revenue",
      "Scale requires millions of Powerwalls enrolled — currently tens of thousands",
      "Long-term: VPP becomes a distributed utility, recurring high-margin revenue",
      "Regulatory complexity varies by state/country — expansion requires approvals",
    ]
  },

  // CORPORATE / BRAND
  {
    id: "brand_recovery",
    label: "Brand Sentiment Recovery",
    category: "corporate",
    weight: 0.04,
    status: "upcoming",
    expected: "Q3 2026",
    likelihood: 0.48,
    updated: "Apr 1, 2026",
    description: [
      "Apr 1, 2026: March registrations TRIPLE in France, DOUBLE in Nordic countries — first hard data of EU demand rebound",
      "Europe: Tesla new car registrations down 28% in 2025 — brand damage documented",
      "Musk DOGE/political involvement strongly correlated with demand drop in EU and blue US states",
      "Vandalism incidents at Tesla dealerships and charging stations increasing in 2025–2026",
      "Brand recovery requires: reduced Musk political visibility, product momentum, positive press",
      "Refreshed Model Y and Cybercab launch are key product catalysts for narrative reset",
      "Brand sentiment ≠ product quality — vehicles still receive top safety/satisfaction ratings",
      "Key signal: if Q2 2026 EU registrations stabilize or recover, sentiment shift is underway",
    ]
  },
  {
    id: "terafab",
    label: "Terafab Chip Factory",
    category: "robotics",
    weight: 0.06,
    status: "upcoming",
    expected: "Q1 2026",
    likelihood: 0.55,
    updated: "Apr 1, 2026",
    description: [
      "Announced by Elon Musk on March 21, 2026 — joint Tesla/SpaceX venture",
      "Goal: build a vertically integrated facility producing 1+ terawatt of AI compute per year",
      "Initial cost: $20B–$25B — NOT included in Tesla's 2026 CapEx guidance",
      "Two chip categories: AI5 inference chips (Tesla vehicles + Optimus) and D3 chips (orbital AI satellites)",
      "Small-batch AI5 production expected 2026 — full fab ramp 2027–2028",
      "Eliminates reliance on TSMC and Nvidia — near-100% vertical integration of AI stack",
      "Actively hiring as of March 26, 2026 (Business Insider confirmed)",
      "Risk: $25B is enormous capital commitment on top of existing $20B+ CapEx plan",
      "Risk: chip fab is notoriously difficult — TSMC took decades to achieve current scale",
    ]
  },
  {
    id: "cortex2",
    label: "Cortex 2.0 Supercomputer",
    category: "robotics",
    weight: 0.05,
    status: "in_progress",
    expected: "Q2 2026",
    likelihood: 0.80,
    updated: "Apr 1, 2026",
    description: [
      "Cortex 2.0 is Tesla's next-generation AI training supercomputer at Giga Texas",
      "First 250MW phase activates April 2026 — full 500MW capacity expected mid-2026",
      "Successor to original Cortex cluster (100MW) — 5x the compute power at full build",
      "Primary purpose: training FSD neural networks and Optimus robot models simultaneously",
      "Reduces dependence on external Nvidia H100/H200 GPU clusters",
      "500MW at full capacity = one of the largest AI compute clusters in the world",
      "Directly enables FSD v14+ improvements and Optimus dexterity training at scale",
      "Timeline confirmed by @JoeTegtmeyer (Mar 7, 2026) — construction visible at Giga Texas",
    ]
  },
  {
    id: "digital_optimus",
    label: "Digital Optimus (Macrohard)",
    category: "robotics",
    weight: 0.05,
    status: "in_progress",
    expected: "Q4 2026",
    likelihood: 0.60,
    updated: "Apr 1, 2026",
    description: [
      "Joint Tesla + xAI project announced March 11, 2026 — nicknamed 'Macrohard' (jab at Microsoft)",
      "Pairs xAI's Grok LLM with a Tesla-developed AI agent for agentic task execution",
      "Musk on X: 'Grok is the master conductor/navigator... directing Digital Optimus, which is processing and actioning the past 5 seconds'",
      "Effectively a software-based Optimus brain — Grok reasons, Tesla agent executes physical tasks",
      "Part of Tesla's investment agreement with xAI — combines both companies' AI capabilities",
      "Business Insider (Mar 2026): some internal tension as xAI's Macrohard effort stalls while Tesla's version ramps",
      "If successful: transforms Optimus from a robot with pre-programmed tasks to a general-purpose AI agent",
      "Key unlock for: complex factory work, external customer deployments, consumer robotics",
      "Risk: multi-company coordination complexity; xAI and Tesla have different incentive structures",
    ]
  },
  // SPACEX MERGER
  {
    id: "spacex_merger",
    label: "SpaceX–Tesla Merger",
    category: "spacex",
    weight: 0.10,
    status: "in_progress",
    expected: "2027–2028",
    likelihood: 0.28,
    updated: "Apr 3, 2026",
    description: [
      "Cross-Equity Inflection Point (Mar 2026): Tesla's $2B xAI investment converted to SpaceX shares after SpaceX acquired xAI — Tesla now holds a direct, albeit small (<1%), stake in SpaceX for the first time",
      "Regulatory filings in March 2026 formally linked the two companies financially — first official cross-entity equity bridge",
      "Musk's 'system-of-systems' vision: Tesla (energy/transport/robotics) + SpaceX (launch/connectivity/interplanetary) converge into a unified platform",
      "Starlink integration thesis: Tesla vehicles as premium Starlink endpoints — always-on high-bandwidth connectivity without cellular dependency",
      "Satellite V2 Mini mass production underway — Starlink at automotive-grade reliability and cost becomes plausible by 2026–2027",
      "Optimus + SpaceX: shared actuator/materials R&D; space-hardened components reduce cost curve for terrestrial robotics",
      "A formal merger or deep partnership would collapse the valuation discount between Tesla (public, volatile) and SpaceX (private, ~$350B latest round)",
      "Bull case: combined entity = largest vertically integrated tech/energy/transport/space company in history — TAM expands beyond any current Tesla model",
      "Bear case: regulatory, shareholder, and conflicts-of-interest barriers remain substantial; SpaceX shareholders resistant to public market exposure",
      "Near-term catalyst watch: any formal joint venture announcement, expanded Starlink Tesla integration, or SEC filings deepening cross-equity",
    ]
  },

  {
    id: "elon_focus",
    label: "Elon Returns Full Focus",
    category: "corporate",
    weight: 0.05,
    status: "upcoming",
    expected: "Q2 2026",
    likelihood: 0.45,
    updated: "Mar 31, 2026",
    description: [
      "Musk's involvement with DOGE (Dept. of Government Efficiency) runs through ~May 2026",
      "Also managing: xAI, X (Twitter), SpaceX, Neuralink, The Boring Company",
      "Tesla investors have consistently expressed concern about time allocation",
      "Q4 2025 earnings call: Musk indicated DOGE role would wind down mid-2026",
      "Historical pattern: Musk refocus on Tesla (e.g., 2019 post-Boring Co) preceded strong execution",
      "Return of full attention = faster decision-making, better product cadence, investor confidence",
      "Sentiment catalyst: any public statement or action signaling Tesla prioritization",
    ]
  },
];

export const links = [
  // Autonomy chain
  { source: "fsd_v13", target: "fsd_unsupervised" },
  { source: "dojo_v2", target: "fsd_unsupervised" },
  { source: "fsd_unsupervised", target: "robotaxi_austin" },
  { source: "fsd_unsupervised", target: "cybercab_production" },
  { source: "regulatory_approval", target: "cybercab_production" },
  { source: "cybercab_production", target: "robotaxi_expansion" },
  { source: "robotaxi_austin", target: "robotaxi_app" },
  { source: "robotaxi_austin", target: "robotaxi_expansion" },
  { source: "regulatory_approval", target: "robotaxi_expansion" },
  { source: "fsd_unsupervised", target: "fsd_licensing" },
  // Robotics chain
  { source: "dojo_v2", target: "optimus_production" },
  { source: "hw5_chip", target: "optimus_production" },
  { source: "optimus_factory", target: "optimus_production" },
  { source: "optimus_production", target: "optimus_external" },
  { source: "dojo_v2", target: "ai_inference" },
  { source: "hw5_chip", target: "ai_inference" },
  // Financial chain
  { source: "delivery_rebound", target: "q1_earnings" },
  { source: "cybercab_production", target: "q1_earnings" },
  { source: "optimus_external", target: "q1_earnings" },
  { source: "delivery_rebound", target: "margin_recovery" },
  { source: "megapack_growth", target: "margin_recovery" },
  { source: "semi_production", target: "margin_recovery" },
  { source: "robotaxi_expansion", target: "margin_recovery" },
  { source: "margin_recovery", target: "share_buyback" },
  { source: "energy_revenue", target: "margin_recovery" },
  { source: "megapack_growth", target: "energy_revenue" },
  { source: "powerwall_ramp", target: "energy_revenue" },
  // Product chain
  { source: "model_y_refresh", target: "delivery_rebound" },
  { source: "affordable_model", target: "delivery_rebound" },
  { source: "cybertruck_profit", target: "margin_recovery" },
  { source: "battery_4680", target: "affordable_model" },
  { source: "battery_4680", target: "cybertruck_profit" },
  { source: "unboxed_process", target: "cybercab_production" },
  { source: "giga_mexico", target: "delivery_rebound" },
  // Corporate chain
  { source: "elon_focus", target: "brand_recovery" },
  { source: "brand_recovery", target: "delivery_rebound" },
  { source: "elon_focus", target: "optimus_production" },
  { source: "fsd_licensing", target: "energy_revenue" },
  { source: "robotaxi_app", target: "robotaxi_expansion" },
  { source: "insurance_profit", target: "margin_recovery" },
  { source: "virtual_powerplant", target: "energy_revenue" },
  { source: "supercharger_network", target: "energy_revenue" },
  { source: "supercharger_network", target: "delivery_rebound" },
  { source: "roadster_reveal", target: "brand_recovery" },
  { source: "roadster_reveal", target: "delivery_rebound" },
  // New 2026 catalysts
  { source: "terafab", target: "hw5_chip" },
  { source: "terafab", target: "ai_inference" },
  { source: "terafab", target: "dojo_v2" },
  { source: "cortex2", target: "fsd_unsupervised" },
  { source: "cortex2", target: "optimus_production" },
  { source: "digital_optimus", target: "optimus_production" },
  { source: "digital_optimus", target: "optimus_external" },
  { source: "elon_focus", target: "digital_optimus" },
  // SpaceX merger chain
  { source: "elon_focus", target: "spacex_merger" },
  { source: "spacex_merger", target: "optimus_external" },
  { source: "spacex_merger", target: "digital_optimus" },
  { source: "spacex_merger", target: "ai_inference" },
];
