// Auto-updated 3x daily by cron — do not edit manually
// Last updated: Apr 1, 2026

export const breakingNews = [
  {
    headline: "Tesla/xAI 'Digital Optimus' (Macrohard) revealed — Grok LLM paired with Tesla AI agent for agentic task execution; joint xAI-Tesla investment project",
    category: "robotics",
    source: "CNBC / Teslarati / Musk on X",
    timestamp: "Mar 11, 2026",
    url: "https://www.cnbc.com/2026/03/11/musk-unveils-joint-tesla-xai-project-macrohard.html",
  },
  {
    headline: "Terafab announced — $20–25B joint Tesla/SpaceX chip fab targeting 1 terawatt AI compute/yr; AI5 chips for vehicles + Optimus, D3 for orbital satellites",
    category: "robotics",
    source: "Business Insider / Electrek",
    timestamp: "Mar 21, 2026",
    url: "https://www.businessinsider.com/elon-musk-terafab-details-spacex-tesla-ai-satellites-terawatt-2026-3",
  },
  {
    headline: "Cortex 2.0 supercomputer confirmed at Giga Texas — first 250MW phase activates April 2026, full 500MW by mid-2026; 5x original Cortex cluster",
    category: "robotics",
    source: "@JoeTegtmeyer / Not a Tesla App",
    timestamp: "Mar 7, 2026",
    url: "https://www.basenor.com/blogs/news/tesla-cortex-2-0-powers-up-in-april-what-it-means-for-optimus",
  },
  {
    headline: "FSD v14.3 hits employee testing — Musk says wide public release expected 'this week'",
    category: "autonomy",
    source: "TeslaNorth",
    timestamp: "Apr 1, 2026",
    url: "https://teslanorth.com/2026/04/01/elon-musk-fsd-14-3-hits-employee-testing-wide-release-expected-this-week/",
  },
  {
    headline: "Tesla discloses robotaxis can be remotely operated by humans — operators in Austin/Palo Alto can drive up to 10 mph",
    category: "autonomy",
    source: "Planetizen / India Today",
    timestamp: "Apr 1, 2026",
    url: "https://www.planetizen.com/news/2026/04/137261-tesla-reveals-remote-drivers-temporarily-control-its-robotaxis",
  },
  {
    headline: "Cybercab production begins April at Giga Texas — expansion to Dallas, Houston, Phoenix, Miami planned H1 2026",
    category: "autonomy",
    source: "247WallSt / Basenor",
    timestamp: "Apr 1, 2026",
    url: "https://247wallst.com/investing/2026/04/01/teslas-path-to-1000-per-share-runs-through-the-autonomous-vehicle-boom/",
  },
  {
    headline: "Tesla loses two more senior leaders ahead of Cybercab production ramp — talent drain continues",
    category: "corporate",
    source: "Austin Statesman / Automotive World",
    timestamp: "Apr 1, 2026",
    url: "https://www.statesman.com/business/article/tesla-cybercab-leaders-departing-elon-musk-22160513.php",
  },
  {
    headline: "Tesla officially ends Model S and Model X production — custom orders closed, inventory only",
    category: "product",
    source: "Business Insider / Inside EVs",
    timestamp: "Apr 1, 2026",
    url: "https://www.businessinsider.com/elon-musk-tesla-model-s-x-orders-discontinued-2026-4",
  },
  {
    headline: "Optimus Gen 3 unveil delayed — Musk says robot is 'walking around' but needs finishing touches; Fremont factory converting to Optimus line targeting 1M units/yr",
    category: "robotics",
    source: "Teslarati / 247WallSt",
    timestamp: "Apr 1, 2026",
    url: "https://www.teslarati.com/elon-musk-announces-disappointing-tesla-optimus-update/",
  },
  {
    headline: "New Tesla Roadster unveil confirmed for late April 2026 — Musk promises 'unveil next month' after years of delays",
    category: "product",
    source: "Electrek",
    timestamp: "Apr 1, 2026",
    url: "https://electrek.co/guides/tesla/",
  },
  {
    headline: "Tesla March registrations triple in France, more than double in Nordic countries — European demand rebound signal",
    category: "financials",
    source: "Reuters",
    timestamp: "Apr 1, 2026",
    url: "https://www.reuters.com/business/retail-consumer/tesla-french-car-registrations-triple-march-2026-04-01/",
  },
  {
    headline: "Q1 2026 delivery report due April 2 — consensus ~365K units, stock up 2% premarket as investors watch for delivery slump inflection",
    category: "financials",
    source: "Yahoo Finance / StockTwits",
    timestamp: "Apr 1, 2026",
    url: "https://finance.yahoo.com/news/tesla-q1-deliveries-expected-to-rebound-slightly-in-challenging-ev-landscape-123741922.html",
  },
  {
    headline: "Netherlands RDW sets April 10, 2026 as hard date for FSD European regulatory approval",
    category: "autonomy",
    source: "Not a Tesla App",
    timestamp: "Mar 23, 2026",
    url: "https://www.notateslaapp.com/news/3826/tesla-fsd-set-for-landmark-european-approval-in-netherlands-next-month",
  },
];
